-- Update 123 hospitals with exact database names (NO license codes in names)
-- These use the exact names from the database

BEGIN;

UPDATE public.hospitals SET name_dv = 'ޙުސައިން ޢަބްދުލް ސަމާދު މެމޮރިއަލް ކްލިނިކް' WHERE name = 'Hussain Abdul Samad Memorial Clinic';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ' WHERE name = 'Vital Care';
UPDATE public.hospitals SET name_dv = 'މެޑްނޮވާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Mednova Medical Center';
UPDATE public.hospitals SET name_dv = 'ޕްރޯ ކެއަރ ކްލިނިކް އެންޑް ޑެންޓަލް ސެންޓަރު' WHERE name = 'Pro Care Clinic and Dental Centre';
UPDATE public.hospitals SET name_dv = 'އިމްޕީރިއަލް މެޑިކެއަރ ސެންޓަރު' WHERE name = 'Imperial Medicare Centre';
UPDATE public.hospitals SET name_dv = 'އާރއެމްއެލް އެސް ލެބް ސާވިސަސް' WHERE name = 'RMLS Lab Services';
UPDATE public.hospitals SET name_dv = 'ޕާރލް މެޑިކަލް ސެންޓަރު' WHERE name = 'Pearl Medical Centre';
UPDATE public.hospitals SET name_dv = 'ޕާރލް މެޑިކަލް ސެންޓަރު ހުޅުމާލެ' WHERE name = 'Pearl Medical Centre Hulhumale';
UPDATE public.hospitals SET name_dv = 'މައި ކްލިނިކް' WHERE name = 'My Clinic';
UPDATE public.hospitals SET name_dv = 'ނޫސަންދާ' WHERE name = 'Noosandha';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ- ކުޅުދުއްފުށި' WHERE name = 'Vital Care- Kulhudhuffushi';
UPDATE public.hospitals SET name_dv = 'މެކް މެޑިކަލް ކްލިނިކް' WHERE name = 'MACL Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ސައުތަން ކެއަރ ކްލިނިކް' WHERE name = 'Southern Care Clinic';
UPDATE public.hospitals SET name_dv = 'މެޑްހޯޕް މެޑިކަލް ސެންޓަރު' WHERE name = 'Medhope Medical Centre';
UPDATE public.hospitals SET name_dv = 'ރިވައިވް މެޑިކަލް ސެންޓަރު' WHERE name = 'Revive Medical Centre';
UPDATE public.hospitals SET name_dv = 'ކުޅުނު މެޑިކަލް ކްލިނިކް' WHERE name = 'Kulunu Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ވެރސޯ މެޑިކަލްސެންޓަރު އަލިފުށި' WHERE name = 'Verso MedicalCentre Alifushi';
UPDATE public.hospitals SET name_dv = 'އިމޭޖް ސެންޓަރު' WHERE name = 'Image Centre';
UPDATE public.hospitals SET name_dv = 'ވިވާޑެންޓް ޑެންޓަލް ސެންޓަރު' WHERE name = 'Vivadent Dental Center';
UPDATE public.hospitals SET name_dv = 'ޓައިނީ ޑްރޮޕްސް މެޑިކަލް ސާވިސަސް' WHERE name = 'Tiny Drops Medical Services';
UPDATE public.hospitals SET name_dv = 'ލޭކޮކާ މެޑިކަލް އެންޑް ރިހެބިލިޓޭޝަން ސެންޓަރު' WHERE name = 'Leykokaa Medical and Rehabilitation Centre';
UPDATE public.hospitals SET name_dv = 'ޕައިން ޓްރީ މެޑިކް ކެއަރ' WHERE name = 'Pine tree Medic Care';
UPDATE public.hospitals SET name_dv = 'ސިނަރްޖީ ކެއަރ' WHERE name = 'Synergy Care';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލްކެއަރ ހުވަދޫ' WHERE name = 'Vitalcare Huvadhoo';
UPDATE public.hospitals SET name_dv = 'އާރއެކްސް މެޑިކެއަރ' WHERE name = 'Rx Medicare';
UPDATE public.hospitals SET name_dv = 'އޯގާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Oagaa Medical Centre';
UPDATE public.hospitals SET name_dv = 'ޕެއިން ކްލިނިކް' WHERE name = 'Pain Clinic';
UPDATE public.hospitals SET name_dv = 'ނައިފަރު މެޑިކަލް ސެންޓަރު' WHERE name = 'Naifaru Medical Center';
UPDATE public.hospitals SET name_dv = 'ޕޮޕިޔުލާ ކްލިނިކް' WHERE name = 'Popular Clinic';
UPDATE public.hospitals SET name_dv = 'ނޫސަންދާ - އައްޑު' WHERE name = 'Noosandha - Addu';
UPDATE public.hospitals SET name_dv = 'މެޑިކްރެސްޓް ކްލިނިކް އެންޑް ޑައިގްނޮސްޓިކްސް' WHERE name = 'Medicrest Clinic and Diagnostics';
UPDATE public.hospitals SET name_dv = 'މޯލްޑިވްސް ނިއުރޯ އެންޑޮކްރައިން މެޑިކަލް ފެސިލިޓީ' WHERE name = 'Maldives Neuro Endocrine Medical Facility';
UPDATE public.hospitals SET name_dv = 'މަގޭ ފިޒިއޯ' WHERE name = 'Magey Physio';
UPDATE public.hospitals SET name_dv = 'ލައިފް ކެއަރ މެޑިކަލް ސެންޓަރު' WHERE name = 'Life Care Medical Centre';
UPDATE public.hospitals SET name_dv = 'ޝިފާ މެޑިކަލް' WHERE name = 'Shifaa Medical';
UPDATE public.hospitals SET name_dv = 'ކާމް މެޑިކަލް' WHERE name = 'Kaam Medical';
UPDATE public.hospitals SET name_dv = 'ލައިފް ވެލްނެސް ކްލިނިކް' WHERE name = 'Life Wellness Clinic';
UPDATE public.hospitals SET name_dv = 'ކުއީން އެސްތެޓިކް މެޑިކަލް ސެންޓަރު' WHERE name = 'Queen Aesthetic Medical Center';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް މެޑިކަލް އެންޑް ޑެންޓަލް ކެއަރ ސެންޓަރު' WHERE name = 'Master Medical and Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'ހާޖީ މެޑިކަލް ކްލިނިކް' WHERE name = 'Haajy Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ހާރޓް ކެއަރ' WHERE name = 'Heart Care';
UPDATE public.hospitals SET name_dv = 'ސްޓާރް މެޑިކަލް' WHERE name = 'Star Medical';
UPDATE public.hospitals SET name_dv = 'ޓީޓީއެޗް ކްލިނިކް' WHERE name = 'TTH Clinic';
UPDATE public.hospitals SET name_dv = 'ލޭބް މޯލްޑިވްސް' WHERE name = 'Lab Maldives';
UPDATE public.hospitals SET name_dv = 'ރިސޯޓް މެޑިކަލް އެންޑް ލެބޮރޭޓްރީ ސާވިސަސް' WHERE name = 'Resort Medical and Laboratory Services';
UPDATE public.hospitals SET name_dv = 'ވިލާ ބައިޔޯ މެޑިކަލްސް ލެބޯރޭޓްރީ' WHERE name = 'Villa Bio Medicals Laboratory';
UPDATE public.hospitals SET name_dv = 'މަފްހާ ޑައިގްނޮސްޓިކް ސެންޓަރު' WHERE name = 'Mafhaa Diagnostic Centre';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކްލިނިކް' WHERE name = 'Physio Clinic';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ އެންޑް އޮޓިޒަމް ކްލިނިކް' WHERE name = 'Physio and Autism Clinic';
UPDATE public.hospitals SET name_dv = 'މައިންޑް ކެއަރ ކްލިނިކް' WHERE name = 'Mindcare Clinic';
UPDATE public.hospitals SET name_dv = 'ނަފްސު ސައިކޮލޮޖިކަލް ސާވިސަސް' WHERE name = 'Nafsu Psychological Services';
UPDATE public.hospitals SET name_dv = 'ކުޅުޙެލަމާ ތެރަޕީ' WHERE name = 'Kulhelama Therapy';
UPDATE public.hospitals SET name_dv = 'ގްރޭޓް މައިންޑްސް' WHERE name = 'Great Minds';
UPDATE public.hospitals SET name_dv = 'އިންސްޓިޓިއުޓް ފޯ ކައުންސިލިންގ އެންޑް ސައިކޮތެރަޕީ' WHERE name = 'Institute For Counselling And Psychotherapy';
UPDATE public.hospitals SET name_dv = 'ތެރަޕީ ސެންޓަރު' WHERE name = 'Therapy Centre';
UPDATE public.hospitals SET name_dv = 'ވީކެއަރ ކައުންސިލިންގ އެންޑް ސައިކޮތެރަޕީ ސެންޓަރު' WHERE name = 'VCare Counselling and Psychotherapy Centre';
UPDATE public.hospitals SET name_dv = 'މައިންޑް ސްޕޭސް' WHERE name = 'Mind Space';
UPDATE public.hospitals SET name_dv = 'ނޯހަބް' WHERE name = 'Knowhub';
UPDATE public.hospitals SET name_dv = 'ވެލްކެއަރ ފިޒިއޮތެރަޕީ އެންޑް ސްޕޯޓްސް ރިހެބިލިޓޭޝަން' WHERE name = 'Wellcare Physiotherapy & Sports Rehabilitation';
UPDATE public.hospitals SET name_dv = 'ހޯޕް ހެލްތް ކެއަރ' WHERE name = 'Hope Health Care';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކިޔުރު' WHERE name = 'Physio Cure';
UPDATE public.hospitals SET name_dv = 'މޫވިންގް ކިޔުރު' WHERE name = 'Moving Cure';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ އެންޑް އޮޓިޒަމް ކްލިނިކް' WHERE name = 'Physio & Autism Clinic - Hulhumale''';
UPDATE public.hospitals SET name_dv = 'ހުވަދޫ ތެރަޕީ ކްލިނިކް' WHERE name = 'Huvadhoo Therapy Clinic';
UPDATE public.hospitals SET name_dv = 'ޓޮޓަލްފިޒިއޯ' WHERE name = 'TotalPhysio';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކްލިނިކް އެނެކްސް 1' WHERE name = 'Physio Clinic Annex 1';
UPDATE public.hospitals SET name_dv = 'ނަޒާ ހެލްތް' WHERE name = 'NazaHealth';
UPDATE public.hospitals SET name_dv = 'މޯލްޑިވްސް އަލްޓަނޭޓިވް މެޑިކަލް ސެންޓަރު' WHERE name = 'Maldives Alternative Medical Centre';
UPDATE public.hospitals SET name_dv = 'ޝާ ތެރަޕީ ދިވެހިބޭސް ސެންޓަރު' WHERE name = 'Sha Therapy Dhivehibeys Centre';
UPDATE public.hospitals SET name_dv = 'ލީފް އޮފް ލައިފް ކްލިނިކް' WHERE name = 'Leaf of Life Clinic';
UPDATE public.hospitals SET name_dv = 'ނޯވޯލް މެޑިކަލް ސެންޓަރު' WHERE name = 'Nowall Medical Centre';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް ޑެންޓަލް ކެއަރ ސެންޓަރު' WHERE name = 'Master Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'އައި ވެއަރ' WHERE name = 'I wear';
UPDATE public.hospitals SET name_dv = 'މިޕްސްޓާރ' WHERE name = 'MIPSTAR';
UPDATE public.hospitals SET name_dv = 'ޓްރޫ ކެއަރ މެޑިކަލްސް' WHERE name = 'True Care Medicals';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ ކުޅުދުއްފުށި އެނެކްސް' WHERE name = 'Vital Care Kulhudhufushi Anex';
UPDATE public.hospitals SET name_dv = 'އައިކޭޓީޓީ މޯލްޑިވްސް' WHERE name = 'ICATT Maldives- Medical Services';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް ޑެންޓަލް ކެއަރ ސެންޓްރޯ' WHERE name = 'Master Dental Care Centro';
UPDATE public.hospitals SET name_dv = 'މައި ޑެންޓަލް ކެއަރ' WHERE name = 'My Dental Care HF -23/ALP/PVT/710';
UPDATE public.hospitals SET name_dv = 'ސްމައިލްސް ޑެންޓަލް ކެއަރ' WHERE name = 'Smiles Dental Care';
UPDATE public.hospitals SET name_dv = 'މައި ފެމިލީ ޑެންޓިސްޓް' WHERE name = 'My Family Dentist';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލްކެއަރ ޑެންޓަލް' WHERE name = 'VitalCare Dental';
UPDATE public.hospitals SET name_dv = 'ސްމައިލްސް ޑެންޓަލް ކެއަރ ހުޅުމާލެ' WHERE name = 'Smiles Dental Care Hulhumale''';
UPDATE public.hospitals SET name_dv = 'މައި ފެމިލީ ޑެންޓިސްޓް މާލެ' WHERE name = 'My Family Dentist Male''';
UPDATE public.hospitals SET name_dv = 'ޕައިން ޓްރީ މެޑިކް ކެއަރ' WHERE name = 'Pine tree Medic Care/ Sh. Funadhoo';
UPDATE public.hospitals SET name_dv = 'އޮމެގާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Omega Medical Centre';
UPDATE public.hospitals SET name_dv = 'މެޑިފްލެކްސް ޑެންޓަލް އެންޑް މެކްސިލޮފޭޝަލް ސާޖަރީ' WHERE name = 'Mediflex Dental and Maxillofacial Surgery';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް' WHERE name = 'Vision Clinic';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް ހުޅުމާލެ' WHERE name = 'Vision Clinic Hulhumale''';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް-1' WHERE name = 'Vision Clinic-1';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކެއަރ އޮޕްޓިކަލް އެންޑް އައި ކްލިނިކް' WHERE name = 'Vision Care Optical and Eye Clinic';
UPDATE public.hospitals SET name_dv = 'މެޑިކާ' WHERE name = 'Medica';
UPDATE public.hospitals SET name_dv = 'މެޑިކާ އެނެކްސް' WHERE name = 'Medica Annex';
UPDATE public.hospitals SET name_dv = 'އައިއެމްޑީސީ މަލްޓި ސްޕެޝަލިޓީ ހޮސްޕިޓަލް' WHERE name = 'I.M.D.C Multi Speciality Hospital';
UPDATE public.hospitals SET name_dv = 'ކުޑަ ވިލިންގިލި' WHERE name = 'Kuda Villingili';
UPDATE public.hospitals SET name_dv = 'ކާގި ކްލިނިކް' WHERE name = 'Kagi Clinic';
UPDATE public.hospitals SET name_dv = 'މާޔަފުށި ކްލިނިކް' WHERE name = 'Maayafushi Clinic';
UPDATE public.hospitals SET name_dv = 'މާމިގިލި ކްލިނިކް' WHERE name = 'Maamigili Clinic';
UPDATE public.hospitals SET name_dv = 'ސަންޑީސް ބަތަލާ އިންފަރމަރީ' WHERE name = 'Sandies Bathala Infirmary';
UPDATE public.hospitals SET name_dv = 'ވެލާ ޕްރައިވެޓް އައިލެންޑް ކްލިނިކް' WHERE name = 'Velaa Private Island Clinic';

COMMIT;
