-- TEMPORARY: Update remaining hospitals with transliterated Dhivehi names
-- These are approximations - replace with exact spellings when available
-- Generated for 95 hospitals from hospitals_missing_dhivehi.csv

BEGIN;

UPDATE public.hospitals SET name_dv = 'އާހިޔާންސް މެޑިކަލް ކްލިނިކް', address_dv = 'އާހިޔާ، ޅ. ހިންނަވަރު' WHERE name = 'Aahiyans Medical Clinic';
UPDATE public.hospitals SET name_dv = 'އަބުހަރީ މެޑިކަލް ސެންޓަރު', address_dv = 'ކުލީ ބިން، ސ. ހިތަދޫ' WHERE name = 'Abuharee Medical Centre';
UPDATE public.hospitals SET name_dv = 'އޭޑީކޭ ހޮސްޕިޓަލް', address_dv = 'ކ.މާލެ، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'ADK Hospital';
UPDATE public.hospitals SET name_dv = 'އޭޑީކޭ ހޮސްޕިޓަލް ރީޗް ކްލިނިކް، މާރަންފުށި', address_dv = 'އޯގާ އާޓް ރިސޯޓްސް، ކ. މާރަންފުށި' WHERE name = 'ADK Hospital Reach Clinic Maaranfushi';
UPDATE public.hospitals SET name_dv = 'އެޑްވާންސް ޑައިގްނޯސްޓިކް ސެންޓަރު', address_dv = 'މީނާޒް، ބ. އޭދަފުށި' WHERE name = 'Advance Diagnostic Center';
UPDATE public.hospitals SET name_dv = 'އެޑްވާންސް އައި ކްލިނިކް', address_dv = 'މ. އެކްސެލް، ކަންބާ އައިސަރާނި ހިންގުން، މާލެ' WHERE name = 'Advance Eye Clinic';
UPDATE public.hospitals SET name_dv = 'އެޑްވާންސް މެޑިކަލް ކްލިނިކް', address_dv = 'ގ. ރޮކެޓްގެ، މާލެ' WHERE name = 'Advance Medical Clinic';
UPDATE public.hospitals SET name_dv = 'އެއިމްސް ޑައިގްނޮސްޓިކް ކެއަރ', address_dv = 'ރިހާބް، ސ. ފޭދޫ' WHERE name = 'Aims Diagnostic Care';
UPDATE public.hospitals SET name_dv = 'އަލައި ޕްލޭ އެންޑް ލަރން ތެރަޕީ ސެންޓަރު', address_dv = 'ހުޅުމާލެ ލޮޓް 11123، ރޯ ހައުސް 13-08' WHERE name = 'Alai Play and Learn Therapy Center';
UPDATE public.hospitals SET name_dv = 'އަލިމަތާ ކްލިނިކް', address_dv = 'ވައުއު އެޓޯލް އަލިމަތާ އަކުއޭޓިކް ރިސޯޓް' WHERE name = 'Alimatha Clinic';
UPDATE public.hospitals SET name_dv = 'އޭއެމްޑީސީ ފިޒިއޮތެރަޕީ ޑިޕާޓްމެންޓް', address_dv = 'މ. މިޞުރުރުވާގެ، ޝާރީވާދީ' WHERE name = 'AMDC Physiotherapy Department';
UPDATE public.hospitals SET name_dv = 'އަމިއްލާ ސިއްޙަތު', address_dv = 'އަމިއްލާ ފުށި، ބ. ފިނޮޅަސް' WHERE name = 'Amilla Sihhath';
UPDATE public.hospitals SET name_dv = 'އަމިންގިރީ ކްލިނިކް', address_dv = 'ހިލްޓަން މޯލްޑިވްސް އަމިންގިރީ ރިސޯޓް އެންޑް ސްޕާ' WHERE name = 'Amingiri Clinic';
UPDATE public.hospitals SET name_dv = 'އަނަންތަރާ ދިގު ކްލިނިކް', address_dv = 'އަނަންތަރާ ރިސޯޓް އެންޑް ސްޕާ މޯލްޑިވްސް، ކ. ދިގުފިނޮޅު' WHERE name = 'Ananatara Dhigu Clinic';
UPDATE public.hospitals SET name_dv = 'އަނަންތަރާ ކިހަވާހް ވިލާ ކްލިނިކް', address_dv = 'އަނަންތަރާ ކިހަވާހް ވިލާސް، ބ. ކިހަވާހް ހުރަވަޅި' WHERE name = 'Anantara Kihavah Villas Clinic';
UPDATE public.hospitals SET name_dv = 'އަންގާގާ މެޑިކަލްސް', address_dv = 'އަންގާގާ އައިލެންޑް ރިސޯޓް އެންޑް ސްޕާ، އދ. އަންގާގާ' WHERE name = 'Angaga Medicals';
UPDATE public.hospitals SET name_dv = 'އަންޒާނާ ވެލަވަރު މެޑިކަލް ސެންޓަރު', address_dv = 'އަންޒާނާ ރިސޯޓް އެންޑް ސްޕާ މޯލްޑިވްސް ވެލަވަރު' WHERE name = 'Angsana Velavaru Medical Centre';
UPDATE public.hospitals SET name_dv = 'އަސީސާ މެޑިކަލް ސެންޓަރު', address_dv = 'ހ. ރަންވެލި، ގްރައުންޑް ފްލޯރ، މާލެ' WHERE name = 'Asisa Medical Center';
UPDATE public.hospitals SET name_dv = 'އަތުރުގާ މެޑިކަލް ކްލިނިކް', address_dv = 'ޑައިމަންޑްސް އަތުރުގާ އައިލެންޑް ރިސޯޓް' WHERE name = 'Athuruga Medical Clinic';
UPDATE public.hospitals SET name_dv = 'އަޔާދާ މޯލްޑިވްސް ރިސޯޓް ކްލިނިކް', address_dv = 'ގދ. މަގުހްދުވާ އައިލެންޑް' WHERE name = 'Ayada Maldives Resort Clinic';
UPDATE public.hospitals SET name_dv = 'އަޒްމީ ނަޢީމް މެޑިކަލް އެންޑް ޑައިގްނޮސްޓިކް ސެންޓަރު', address_dv = 'މ. މިޞުރުވާގެ، ޝާރީވަރުދީ މަގު، މާލެ' WHERE name = 'Azmi Naeem Medical & Diagnostic Centre';
UPDATE public.hospitals SET name_dv = 'ބަރޯސް ކްލިނިކް', address_dv = 'ބަރޯސް މޯލްޑިވްސް، ކ. ބަރޯސް' WHERE name = 'Baros Clinic';
UPDATE public.hospitals SET name_dv = 'ބީކެއަރ', address_dv = 'ބާސެލޯ ވޭލް ލަގޫން މޯލްޑިވްސް، އދ. ބޮޑުފިނޮޅު' WHERE name = 'BCare';
UPDATE public.hospitals SET name_dv = 'ބްލިސް ކެއަރ', address_dv = 'ގުލްޒާރުގެ، ޅ. ނައިފަރު' WHERE name = 'Bliss Care';
UPDATE public.hospitals SET name_dv = 'ބްލައިސް މަލްޓި-ސްޕެޝަލިޓީ ތެރަޕީ ސެންޓަރު', address_dv = 'ހުޅުމާލެ، ލޮޓް 10505' WHERE name = 'Blyss Multi-Speciality Therapy Centre';
UPDATE public.hospitals SET name_dv = 'ބޮލިފުށި ކްލިނިކް', address_dv = 'ބޮލިފުށި އައިލެންޑް ރިސޯޓް، ކ. ބޮލިފުށި' WHERE name = 'Bolifushi Clinic';
UPDATE public.hospitals SET name_dv = 'ބުލްބުލް ތެރަޕީ ކްލިނިކް', address_dv = 'ހެދޭކުރި، ހދ. ކުޅުދުއްފުށި' WHERE name = 'Bulbul Therapy Clinic';
UPDATE public.hospitals SET name_dv = 'ކެއަރ މެކްސް ކްލިނިކް 1', address_dv = 'ތާޖް ކޯރަލް ރީފް އެންޑް ސްޕާ، މޯލްޑިވްސް' WHERE name = 'Care Max Clinic 1';
UPDATE public.hospitals SET name_dv = 'ކެއަރ މެޑިކަލްސް ސާވިސަސް', address_dv = 'މާ. ނޫރިހީ، 1 ވަނަ ފަންގިފިލާ، ކާމީނީމަގު' WHERE name = 'Care Medicals Services';
UPDATE public.hospitals SET name_dv = 'ކެއަރ ޓްރަސްޓް މަލްޓި ސްޕެޝަލިޓީ ކްލިނިކް', address_dv = 'އެޗްއެމް ކޮމާޝަލް ޔުނިޓް، ހުވަންދުމާ ހިންގުން، މާލެ' WHERE name = 'Care Trust Multi Speciality Clinic';
UPDATE public.hospitals SET name_dv = 'ކެއަރވަން ޑެންޓަލް އެންޑް ކްލިނިކް', address_dv = 'ހ. ނިވާދި' WHERE name = 'Careone Dental & Clinic';
UPDATE public.hospitals SET name_dv = 'ސެންޓްރަލް ކްލިނިކް', address_dv = '1 ވަނަ ފަންގިފިލާ، މ. ދިހްލީ ވިލާ، މާލެ' WHERE name = 'Central Clinic';
UPDATE public.hospitals SET name_dv = 'ސެންޓްރަލް މެޑިކަލް ސެންޓަރު', address_dv = '1 ވަނަ ފަންގިފިލާ އެންޑް 2 ވަނަ ފަންގިފިލާ، މ.ނިމްސާ، މާލެ' WHERE name = 'Central Medical Center';
UPDATE public.hospitals SET name_dv = 'ސެންޓަރ ފޯ ޓްރެޑިޝަނަލް މެޑިސިން', address_dv = 'މާ. މާތަނޑީ، މާލެ' WHERE name = 'Centre for Traditional Medicine';
UPDATE public.hospitals SET name_dv = 'ޝެވަލް ބްލާންސް ރަންދެލި ކްލިނިކް', address_dv = 'ޝެވަލް ބްލާންކް ރަންދެލި، ނ.އެޓޯލް' WHERE name = 'Cheval Blance Randeli Clinic';
UPDATE public.hospitals SET name_dv = 'ޗައިލްޑް ޑިވެލޮޕްމަންޓް ކްލިނިކް', address_dv = '3357033' WHERE name = 'Child Development Clinic';
UPDATE public.hospitals SET name_dv = 'ޗައިނީޒް ހެލްތް ކެއަރ', address_dv = 'ގ. މާޖެހީގެ، 1 ވަނަ ފަންގިފިލާ، ލިލީ މަގު، މާލެ' WHERE name = 'Chinese Health Care';
UPDATE public.hospitals SET name_dv = 'ސިނަމަން ދޮންވެލި މޯލްޑިވްސް މެޑިކަލް ކްލިނިކް', address_dv = 'ސިނަމަން ދޮންވެލި މޯލްޑިވްސް' WHERE name = 'Cinnamon Dhonveli Maldives Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ސިނަމަން ވެލިފުށި މޯލްޑިވްސް މެޑިކަލް ކްލިނިކް', address_dv = 'ސިނަމަން ވެލިފުށި މޯލްޑިވްސް، ވ. އާރަށް' WHERE name = 'Cinnamon Velifushi Maldives Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ސިޓީ އޮޕްޓިކަލްސް', address_dv = 'އާރ9-05، 2 ވަނަ ފަންގިފިލާ، ހިތިގަސް މަގު، ހުޅުމާލެ' WHERE name = 'City Opticals';
UPDATE public.hospitals SET name_dv = 'ކޯކޯއިސްލަންޑް ކްލިނިކް', address_dv = 'ކޯކޯ އައިލެންޑް، ކ. މަކުނުފުށި' WHERE name = 'Cocoa Island Island';
UPDATE public.hospitals SET name_dv = 'ކޯކޮގިރީ ކްލިނިކް', address_dv = 'ވަޝުގިރީ، ވައުއު އެޓޯލް' WHERE name = 'Cocogiri Clinic';
UPDATE public.hospitals SET name_dv = 'ކޮންސްޓަންސް މޫފުށި ރިސޯޓް ކްލިނިކް', address_dv = 'ކޮންސްޓަންސް މޫފުށި ރިސޯޓް، ސައުތް އަރީ އެޓޯލް' WHERE name = 'Constance Moofushi Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ޑީ.އެސް.އެމް ކްލިނިކް', address_dv = 'ހ. ދިއްގާ މާގެ، މާލެ' WHERE name = 'D.S.M Clinic';
UPDATE public.hospitals SET name_dv = 'ޑެންޓަލް ކެއަރ ސެންޓަރު', address_dv = 'މާ. މޭވާގަސްދޯޝުގެ، 1 ވަނަ ފަންގިފިލާ' WHERE name = 'Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'ޑެންޓަލް ސްޓޫޑިއޯ', address_dv = 'އާމީން އެވެނީޔު، ރީތިގަސް މަގު، ހުޅުމާލެ' WHERE name = 'Dental Studio';
UPDATE public.hospitals SET name_dv = 'ދަރަވަންދޫ މެޑިކަލް ސެންޓަރު', address_dv = 'ހަމަވާތި، ބ. ދަރަވަންދޫ' WHERE name = 'Dharavandhoo Medical Center';
UPDATE public.hospitals SET name_dv = 'ދިވެހި ބޭސް ކްލިނިކް', address_dv = 'ލޮޓް ނައް 10176، ހުޅުމާލެ' WHERE name = 'Dhivehi Beys Clinic';
UPDATE public.hospitals SET name_dv = 'ދުނިދޫ ކްލިނިކް', address_dv = 'ދުނިދޫ އޮފިސް ބިލްޑިންގ، ކ. ދުނިދޫ' WHERE name = 'Dhoonidhoo Clinic';
UPDATE public.hospitals SET name_dv = 'ދުގެތި ދިވެހިބޭސް ކްލިނިކް', address_dv = 'މާ. ފޯރސިތިޔާ، މާލެ' WHERE name = 'Dhugethi Dhivehibeys Clinic';
UPDATE public.hospitals SET name_dv = 'ޑރ. ކްލިނިކް', address_dv = 'މާފުށިވަރު މޯލްޑިވްސް، އދ. މާފުށިވަރު' WHERE name = 'Doctor''s Clinic';
UPDATE public.hospitals SET name_dv = 'ޑރ. ދީދީ ޑެންޓަލް އެންޑް މެޑިކަލް ސެންޓަރު', address_dv = 'ލޮޓް ނައް 10409، އަހިގަސް މަގު، ހުޅުމާލެ' WHERE name = 'Dr Didi Dental And Medical Center';
UPDATE public.hospitals SET name_dv = 'ޑރ. އުސާމާ ޑެންޓަލް ކްލިނިކް', address_dv = 'ހ. ރެލިކް، ހަކުރާ ގޯޅި، މާލެ' WHERE name = 'Dr Usama Dental Clinic';
UPDATE public.hospitals SET name_dv = 'ޑރ. ދީދީ ޑެންޓަލް ސެންޓަރު', address_dv = 'ގ. ދަތުގެ، މާލެ' WHERE name = 'Dr. Didi Dental Centre';
UPDATE public.hospitals SET name_dv = 'ޑރ. ޖިހާދުގެ މެޑިކަލް އެންޑް ޑެންޓަލް ސެންޓަރު', address_dv = 'މާ.ރެޑް ރޯސް ހުޅަނގުބައި، ބުރުޒުމަގު، މާލެ' WHERE name = 'Dr. Jihad''s Medical and Dental Centre';
UPDATE public.hospitals SET name_dv = 'ޑރ. އުސާމާގެ ކްލިނިކް މާފަންނު', address_dv = 'މ. ގްރީން ލައިފް، މާލެ' WHERE name = 'Dr. Usama''s Clinic Maafannu';
UPDATE public.hospitals SET name_dv = 'ޑްރީމް ލޭންޑް ކްލިނިކް', address_dv = 'ޑްރީމްލޭންޑް ދި ޔުނިކް ސީ އެންޑް ލޭކް ރިސޯޓް ސްޕާ، ބ. ހިރުންދޫ' WHERE name = 'Dream Land Clinic';
UPDATE public.hospitals SET name_dv = 'އަރލީ އިންޓަވެންޝަން ތެރަޕީ ސެންޓަރު', address_dv = 'ގ. ކާކާގެ އާގެ، މާލެ' WHERE name = 'Early Intervention Therapy Centre';
UPDATE public.hospitals SET name_dv = 'އެލައިޓް މެޑިކަލް ސެންޓަރު', address_dv = 'މާ. ބޯގެ، މާލެ' WHERE name = 'Elite Medical Centre';
UPDATE public.hospitals SET name_dv = 'އެލްލައިދޫ ކްލިނިކް', address_dv = 'އެލްލައިދޫ، އއ. އެޓޯލް' WHERE name = 'Ellaidhoo Clinic';
UPDATE public.hospitals SET name_dv = 'އެމަރަލްޑް ޑެންޓަލް ކެއަރ', address_dv = 'ލޮޓް ނައް 11157، ހުޅުމާލެ' WHERE name = 'Emerald Dental Care';
UPDATE public.hospitals SET name_dv = 'އެމަރަލްޑް ފާރޫޝި ކްލިނިކް', address_dv = 'ފާރޫޝި އައިލެންޑް، ރ. އެޓޯލް' WHERE name = 'Emerald Faarushi Clinic';
UPDATE public.hospitals SET name_dv = 'އެމަރަލްޑް މޯލްޑިވްސް ރިސޯޓް ކްލިނިކް', address_dv = 'ރ. ފަސްމެންދޫ އައިލެންޑް' WHERE name = 'Emerald Maldives Resort Clinic';
UPDATE public.hospitals SET name_dv = 'އެރި މޯލްޑިވްސް ކްލިނިކް', address_dv = 'އިޔާދޫ އައިލެންޑް، ކާފު އެޓޯލް' WHERE name = 'Eri Maldives Clini';
UPDATE public.hospitals SET name_dv = 'އެރިޔާދޫ ކްލިނިކް', address_dv = 'އެރިޔާދޫ އައިލެންޑް ރިސޯޓް' WHERE name = 'Eriyadu Clinic';
UPDATE public.hospitals SET name_dv = 'އީވް ކްލިނިކް', address_dv = 'މ. ކޮވާރިކް، މާލެ' WHERE name = 'Eve Clinic';
UPDATE public.hospitals SET name_dv = 'އައި ކެއަރ ކްލިނިކް (އައްޑު ބްރާންޗް)', address_dv = 'ސިލްވަރ ލީފް، ހިޔްފަސޭޙާ މަގު، ސ.ހިތަދޫ' WHERE name = 'Eye Care Clinic (Addu Branch)';
UPDATE public.hospitals SET name_dv = 'އައި ކެއަރ ހޮސްޕިޓަލް', address_dv = 'މ.އުޝާ، އޯކިޑް މަގު، މާލެ' WHERE name = 'Eye Care Hospital';
UPDATE public.hospitals SET name_dv = 'އައި ކެއަރ ހޮސްޕިޓަލް ހުޅުމާލެ އެނެކްސް', address_dv = 'ލޮޓް 10420، ހުޅުމާލެ' WHERE name = 'Eye Care Hospital Hulhumale'' Annex';
UPDATE public.hospitals SET name_dv = 'އައި ޓޫ އައި އޮޕްޓިކަލްސް އެންޑް ކްލިނިކް', address_dv = 'މ. ސިލޭޙާ، ފުނަގޯޅި' WHERE name = 'Eye to Eye Opticals & Clinic';
UPDATE public.hospitals SET name_dv = 'އައި ޓޫ އައި އޮޕްޓިކަލްސް އެންޑް ކްލިނިކް 2', address_dv = 'މ. ދިޔާނެރު' WHERE name = 'Eye to Eye Opticals & Clinic 2';
UPDATE public.hospitals SET name_dv = 'އައިކެއަރ އޮޕްޓިކަލްސް (ފުވައްމުލައް ބްރާންޗް)', address_dv = 'މ. ޖުޕިޓަރް ފަރީދީ މަގު، މާލެ' WHERE name = 'Eyecare opticals (fuvahmulah branch)';
UPDATE public.hospitals SET name_dv = 'އެފް އެންޑް ސީ މެޑިކެއަރ އެންޑް ސްކޭން ސެންޓަރު', address_dv = 'އެހާރު، ސ. ހިތަދޫ' WHERE name = 'F & C Medicare and Scan Center';
UPDATE public.hospitals SET name_dv = 'އެފް އެންޑް ސީ ޕްރައިމް ކެއަރ', address_dv = 'ތިލަފުށި އޮފިސް، ކ.ތިލަފުށި' WHERE name = 'F & C Prime Care';
UPDATE public.hospitals SET name_dv = 'އެފް އެންޑް ސީ މެޑިކެއަރ، މީދޫ', address_dv = 'މިރިހާނާ، ސ. މީދޫ' WHERE name = 'F&C Medicare Meedhoo';
UPDATE public.hospitals SET name_dv = 'ފެމިލީ ކެއަރ ކްލިނިކް އެންޑް ސްކޭން ސެންޓަރު', address_dv = 'ހ. އަޒުން، އާމީނީ މަގު، މާލެ' WHERE name = 'Family Care Clinic and Scan Centre';
UPDATE public.hospitals SET name_dv = 'ފެމިލީ ޑެންޓަލް ކެއަރ', address_dv = 'ސަން އީސްޓް 2 ވަނަ ފަންގިފިލާ، ނިރޯޅު މަގު' WHERE name = 'Family Dental Care';
UPDATE public.hospitals SET name_dv = 'ފެމިލީ ރިލޭޝަންޝިޕް ސާވިސަސް', address_dv = 'މާ. މާފޮޅޭވިލާ، ގްރައުންޑް ފްލޯރ، މާލެ' WHERE name = 'Family Relationship Services';
UPDATE public.hospitals SET name_dv = 'ފަރޫކް ހެލްތްކެއަރ', address_dv = 'ރަންދަން، ގނ. ފުވައްމުލައް' WHERE name = 'Farook Healthcare';
UPDATE public.hospitals SET name_dv = 'ފަރޫކް ހެލްތްކެއަރ ވިލިނގިލި', address_dv = 'ބްލޫ ހައުސް، ގއ. ވިލިނގިލި' WHERE name = 'Farook Healthcare Villingili';

COMMIT;
