-- FINAL PART 2: Remaining 74 hospitals with EXACT database names
-- Run this AFTER update_hospitals_exact_final.sql

BEGIN;

UPDATE public.hospitals SET name_dv = 'ޕާރލް މެޑިކަލް ސެންޓަރު ހުޅުމާލެ' WHERE name = 'Pearl Medical Centre Hulhumale';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ އެންޑް އޮޓިޒަމް ކްލިނިކް' WHERE name = 'Physio & Autism Clinic - Hulhumale''';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ އެންޑް އޮޓިޒަމް ކްލިނިކް' WHERE name = 'Physio and Autism Clinic';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކްލިނިކް' WHERE name = 'Physio Clinic';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކްލިނިކް އެނެކްސް 1' WHERE name = 'Physio Clinic Annex 1';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކިޔުރު' WHERE name = 'Physio Cure';
UPDATE public.hospitals SET name_dv = 'ޕައިން ޓްރީ މެޑިކް ކެއަރ' WHERE name = 'Pine tree Medic Care';
UPDATE public.hospitals SET name_dv = 'ޕޮޕިޔުލާ ކްލިނިކް' WHERE name = 'Popular Clinic';
UPDATE public.hospitals SET name_dv = 'ޕްރޯ ކެއަރ ކްލިނިކް އެންޑް ޑެންޓަލް ސެންޓަރު' WHERE name = 'Pro Care Clinic and Dental Centre';
UPDATE public.hospitals SET name_dv = 'ޕުލްމަން މޯލްޑިވްސް މާމުތާ ރިސޯޓް ކްލިނިކް' WHERE name = 'Pullman Maldives Maamutaa Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ކުއީން އެސްތެޓިކް މެޑިކަލް ސެންޓަރު' WHERE name = 'Queen Aesthetic Medical Center';
UPDATE public.hospitals SET name_dv = 'ރާޔާ ކްލިނިކް' WHERE name = 'Raaya Clinic';
UPDATE public.hospitals SET name_dv = 'ރެފްލްސް ކްލިނިކް' WHERE name = 'Raffles Clinic';
UPDATE public.hospitals SET name_dv = 'ރަންގާލި ކްލިނިކް' WHERE name = 'Rangali Clinic';
UPDATE public.hospitals SET name_dv = 'ރަންނާލި ކްލިނިކް' WHERE name = 'Rannalhi Clinic HF22/ALP/PVT/659';
UPDATE public.hospitals SET name_dv = 'ރަސްފުށި ކްލިނިކް' WHERE name = 'Rasfushi Clinic';
UPDATE public.hospitals SET name_dv = 'ރީތި ބީޗް ކްލިނިކް' WHERE name = 'Reethi Beach Clilnic HF -23/ALP/PVT/711';
UPDATE public.hospitals SET name_dv = 'ރީތި ފަރު ކްލިނިކް' WHERE name = 'Reethi Faru Clinic';
UPDATE public.hospitals SET name_dv = 'ރިސޯޓް ކްލިނިކް' WHERE name = 'Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ރިސޯޓް މެޑިކަލް އެންޑް ލެބޮރޭޓްރީ ސާވިސަސް' WHERE name = 'Resort Medical and Laboratory Services';
UPDATE public.hospitals SET name_dv = 'ރިވައިވް މެޑިކަލް ސެންޓަރު' WHERE name = 'Revive Medical Centre';
UPDATE public.hospitals SET name_dv = 'އާރއެމްއެލް އެސް ލެބް ސާވިސަސް' WHERE name = 'RMLS Lab Services';
UPDATE public.hospitals SET name_dv = 'ރުގަލު ކްލިނިކް' WHERE name = 'Ruhgalu Clinic';
UPDATE public.hospitals SET name_dv = 'އާރއެކްސް މެޑިކެއަރ' WHERE name = 'Rx Medicare';
UPDATE public.hospitals SET name_dv = 'ސަންޑީސް ބަތަލާ އިންފަރމަރީ' WHERE name = 'Sandies Bathala Infirmary';
UPDATE public.hospitals SET name_dv = 'ޝާ ތެރަޕީ ދިވެހިބޭސް ސެންޓަރު' WHERE name = 'Sha Therapy Dhivehibeys Centre';
UPDATE public.hospitals SET name_dv = 'ޝިފާ މެޑިކަލް' WHERE name = 'Shifaa Medical';
UPDATE public.hospitals SET name_dv = 'ސިކްސް ސެންސިސް ލާމު ކްލިނިކް' WHERE name = 'Six Sensus Laamu Clinic';
UPDATE public.hospitals SET name_dv = 'ސިޔާމް ވޯރްލްޑް މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Siyam World Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސްމައިލްސް ޑެންޓަލް ކެއަރ' WHERE name = 'Smiles Dental Care';
UPDATE public.hospitals SET name_dv = 'ސްމައިލްސް ޑެންޓަލް ކެއަރ ހުޅުމާލެ' WHERE name = 'Smiles Dental Care Hulhumale''';
UPDATE public.hospitals SET name_dv = 'އެސްއޯ މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'SO/ Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސޮނެވާ ފުށި ކްލިނިކް' WHERE name = 'Soneva Fushi Clinic';
UPDATE public.hospitals SET name_dv = 'ސޮނެވާ ޖާނި ކްލިނިކް' WHERE name = 'Soneva Jani Clinic';
UPDATE public.hospitals SET name_dv = 'ސައުތަން ކެއަރ ކްލިނިކް' WHERE name = 'Southern Care Clinic';
UPDATE public.hospitals SET name_dv = 'ސްޓާރް މެޑިކަލް' WHERE name = 'Star Medical';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް އިރުފުށި މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Sun Siyam Irufushi Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް އިރުވެލި މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Sun Siyam Iruveli Maldives Clinic HF -23/ALP/PVT/709';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް އޮޅުވެލި މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Sun Siyam Olhuveli Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް ވިލު ރީފް މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Sun Siyam Vilu Reef Maldives CLinic';
UPDATE public.hospitals SET name_dv = 'ސިނަރްޖީ ކެއަރ' WHERE name = 'Synergy Care';
UPDATE public.hospitals SET name_dv = 'ތާޖް އެކްޒޮޓިކާ ކްލިނިކް' WHERE name = 'Taj Exotica Clinic';
UPDATE public.hospitals SET name_dv = 'ދަ ރެޒިޑެންސް މޯލްޑިވްސް އެޓް ދިގުރާ ކްލިނިކް' WHERE name = 'The Residence Maldives at Dhigurah Clinic';
UPDATE public.hospitals SET name_dv = 'ދަ ސްޓެންޑާޑް ކްލިނިކް' WHERE name = 'The Standard Clinic';
UPDATE public.hospitals SET name_dv = 'ތެރަޕީ ސެންޓަރު' WHERE name = 'Therapy Centre';
UPDATE public.hospitals SET name_dv = 'ތިލަމާފުށި ކްލިނިކް' WHERE name = 'Thilamaafushi Clinic';
UPDATE public.hospitals SET name_dv = 'ތުނޑުފުށި މެޑިކަލް ކްލިނިކް' WHERE name = 'Thudufushi Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ތުޅަގިރި ކްލިނިކް' WHERE name = 'Thulhagiri Clinic';
UPDATE public.hospitals SET name_dv = 'ޓައިނީ ޑްރޮޕްސް މެޑިކަލް ސާވިސަސް' WHERE name = 'Tiny Drops Medical Services';
UPDATE public.hospitals SET name_dv = 'ޓޮޓަލްފިޒިއޯ' WHERE name = 'TotalPhysio';
UPDATE public.hospitals SET name_dv = 'ޓްރޫ ކެއަރ މެޑިކަލްސް' WHERE name = 'True Care Medicals';
UPDATE public.hospitals SET name_dv = 'ޓީޓީއެޗް ކްލިނިކް' WHERE name = 'TTH Clinic';
UPDATE public.hospitals SET name_dv = 'ވާދޫ ކްލިނިކް' WHERE name = 'Vadoo Clinic HF -23/ALP/PVT/708';
UPDATE public.hospitals SET name_dv = 'ވަރު މެޑިކަލް ސެންޓަރު' WHERE name = 'Varu Medical Centre';
UPDATE public.hospitals SET name_dv = 'ވީކެއަރ ކައުންސިލިންގ އެންޑް ސައިކޮތެރަޕީ ސެންޓަރު' WHERE name = 'VCare Counselling and Psychotherapy Centre';
UPDATE public.hospitals SET name_dv = 'ވެލާ ޕްރައިވެޓް އައިލެންޑް ކްލިނިކް' WHERE name = 'Velaa Private Island Clinic';
UPDATE public.hospitals SET name_dv = 'ވެލަސަރު މެޑިކަލް ސެންޓަރު' WHERE name = 'Velassaru Medical Center';
UPDATE public.hospitals SET name_dv = 'ވެލިގަނޑު ކްލިނިކް' WHERE name = 'Veligandu Clinic HF -23/ALP/PVT/704';
UPDATE public.hospitals SET name_dv = 'ވެރސޯ މެޑިކަލްސެންޓަރު އަލިފުށި' WHERE name = 'Verso MedicalCentre Alifushi';
UPDATE public.hospitals SET name_dv = 'ވިލާ ބައިޔޯ މެޑިކަލްސް ލެބޯރޭޓްރީ' WHERE name = 'Villa Bio Medicals Laboratory';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކެއަރ އޮޕްޓިކަލް އެންޑް އައި ކްލިނިކް' WHERE name = 'Vision Care Optical and Eye Clinic';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް' WHERE name = 'Vision Clinic';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް ހުޅުމާލެ' WHERE name = 'Vision Clinic Hulhumale''';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް-1' WHERE name = 'Vision Clinic-1';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ' WHERE name = 'Vital Care';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ ކުޅުދުއްފުށި އެނެކްސް' WHERE name = 'Vital Care Kulhudhufushi Anex';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ- ކުޅުދުއްފުށި' WHERE name = 'Vital Care- Kulhudhuffushi';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލްކެއަރ ޑެންޓަލް' WHERE name = 'VitalCare Dental';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލްކެއަރ ހުވަދޫ' WHERE name = 'Vitalcare Huvadhoo';
UPDATE public.hospitals SET name_dv = 'ވިވާޑެންޓް ޑެންޓަލް ސެންޓަރު' WHERE name = 'Vivadent Dental Center';
UPDATE public.hospitals SET name_dv = 'ވޮމުލި ކްލިނިކް' WHERE name = 'Vommuli Clinic';
UPDATE public.hospitals SET name_dv = 'ވެލްކެއަރ ފިޒިއޮތެރަޕީ އެންޑް ސްޕޯޓްސް ރިހެބިލިޓޭޝަން' WHERE name = 'Wellcare Physiotherapy & Sports Rehabilitation';
UPDATE public.hospitals SET name_dv = 'ޔޫ އެންޑް މީ ކްލިނިކް' WHERE name = 'You & Me Clinic';

COMMIT;
