-- UPDATE: Dhivehi addresses for 174 hospitals - Part 2 (P-Z)

BEGIN;

UPDATE public.hospitals SET address_dv = 'ޕޭން ކްލިނިކް، ފެސްދު އައިލެންޑް، ނޯތް އަރި އަތޮޅު، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Ouch';
UPDATE public.hospitals SET address_dv = 'ޕާރލް މެޑިކަލް ސެންޓަރު، މ. ޗަންބޭލީގެ، ޝާރީވަރުދީ، މާލެ، މޯލްޑިވްސް' WHERE name = 'Pearl Medical Centre';
UPDATE public.hospitals SET address_dv = 'ހުޅުމާލެ' WHERE name = 'Pearl Medical Centre Hulhumale';
UPDATE public.hospitals SET address_dv = 'ހިޔާ ހުޅުމާލެ' WHERE name = 'Physio & Autism Clinic - Hulhumale''';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Physio and Autism Clinic';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Physio Clinic';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Physio Clinic Annex 1';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Physio Cure';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Pine tree Medic Care';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Popular Clinic';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Pro Care Clinic and Dental Centre';
UPDATE public.hospitals SET address_dv = 'ޕުލްމަން މޯލްޑިވްސް މާމުތާ ރިސޯޓް' WHERE name = 'Pullman Maldives Maamutaa Resort Clinic';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Queen Aesthetic Medical Center';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Raaya Clinic';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Raffles Clinic';
UPDATE public.hospitals SET address_dv = 'ރަންގާލި އައިލެންޑް' WHERE name = 'Rangali Clinic';
UPDATE public.hospitals SET address_dv = 'ރަންނާލި އައިލެންޑް' WHERE name = 'Rannalhi Clinic HF22/ALP/PVT/659';
UPDATE public.hospitals SET address_dv = 'ރަސްފުށި އައިލެންޑް' WHERE name = 'Rasfushi Clinic';
UPDATE public.hospitals SET address_dv = 'ރީތި ބީޗް އައިލެންޑް' WHERE name = 'Reethi Beach Clilnic HF -23/ALP/PVT/711';
UPDATE public.hospitals SET address_dv = 'ރީތި ފަރު އައިލެންޑް' WHERE name = 'Reethi Faru Clinic';
UPDATE public.hospitals SET address_dv = 'ރިސޯޓް އައިލެންޑް' WHERE name = 'Resort Clinic';
UPDATE public.hospitals SET address_dv = 'ރިސޯޓް އައިލެންޑް' WHERE name = 'Resort Medical and Laboratory Services';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Revive Medical Centre';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'RMLS Lab Services';
UPDATE public.hospitals SET address_dv = 'ރުގަލު އައިލެންޑް' WHERE name = 'Ruhgalu Clinic';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Rx Medicare';
UPDATE public.hospitals SET address_dv = 'ސަންޑީސް ބަތަލާ އައިލެންޑް' WHERE name = 'Sandies Bathala Infirmary';
UPDATE public.hospitals SET address_dv = 'ޝާ ތެރަޕީ ސެންޓަރު، މާލެ' WHERE name = 'Sha Therapy Dhivehibeys Centre';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Shifaa Medical';
UPDATE public.hospitals SET address_dv = 'ސިކްސް ސެންސިސް ލާމު އައިލެންޑް' WHERE name = 'Six Sensus Laamu Clinic';
UPDATE public.hospitals SET address_dv = 'ސިޔާމް ވޯރްލްޑް މޯލްޑިވްސް އައިލެންޑް' WHERE name = 'Siyam World Maldives Clinic';
UPDATE public.hospitals SET address_dv = 'މާލެ' WHERE name = 'Smiles Dental Care';
UPDATE public.hospitals SET address_dv = 'ހުޅުމާލެ' WHERE name = 'Smiles Dental Care Hulhumale''';
UPDATE public.hospitals SET address_dv = 'އެސްއޯ މޯލްޑިވްސް އައިލެންޑް' WHERE name = 'SO/ Maldives Clinic';
UPDATE public.hospitals SET address_dv = 'ސޮނެވާ ފުށި އައިލެންޑް' WHERE name = 'Soneva Fushi Clinic';
UPDATE public.hospitals SET address_dv = 'ސޮނެވާ ޖާނި އައިލެންޑް' WHERE name = 'Soneva Jani Clinic';
UPDATE public.hospitals SET address_dv = 'ސައުތަން ކެއަރ އައިލެންޑް' WHERE name = 'Southern Care Clinic';
UPDATE public.hospitals SET address_dv = 'ސްޓާރް މެޑިކަލް، މާލެ' WHERE name = 'Star Medical';
UPDATE public.hospitals SET address_dv = 'ސަން ސިޔާމް އިރުފުށި މޯލްޑިވްސް އައިލެންޑް' WHERE name = 'Sun Siyam Irufushi Maldives Clinic';
UPDATE public.hospitals SET address_dv = 'ސަން ސިޔާމް އިރުވެލި މޯލްޑިވްސް އައިލެންޑް' WHERE name = 'Sun Siyam Iruveli Maldives Clinic HF -23/ALP/PVT/709';
UPDATE public.hospitals SET address_dv = 'ސަން ސިޔާމް އޮޅުވެލި މޯލްޑިވްސް އައިލެންޑް' WHERE name = 'Sun Siyam Olhuveli Maldives Clinic';
UPDATE public.hospitals SET address_dv = 'ސަން ސިޔާމް ވިލު ރީފް މޯލްޑިވްސް އައިލެންޑް' WHERE name = 'Sun Siyam Vilu Reef Maldives CLinic';
UPDATE public.hospitals SET address_dv = 'ސިނަރްޖީ ކެއަރ، މާލެ' WHERE name = 'Synergy Care';
UPDATE public.hospitals SET address_dv = 'ތާޖް އެކްޒޮޓިކާ އައިލެންޑް' WHERE name = 'Taj Exotica Clinic';
UPDATE public.hospitals SET address_dv = 'ދަ ރެޒިޑެންސް މޯލްޑިވްސް އެޓް ދިގުރާ އައިލެންޑް' WHERE name = 'The Residence Maldives at Dhigurah Clinic';
UPDATE public.hospitals SET address_dv = 'ދަ ސްޓެންޑާޑް އައިލެންޑް' WHERE name = 'The Standard Clinic';
UPDATE public.hospitals SET address_dv = 'ތެރަޕީ ސެންޓަރު، މާލެ' WHERE name = 'Therapy Centre';
UPDATE public.hospitals SET address_dv = 'ތިލަމާފުށި އައިލެންޑް' WHERE name = 'Thilamaafushi Clinic';
UPDATE public.hospitals SET address_dv = 'ތުނޑުފުށި މެޑިކަލް އައިލެންޑް' WHERE name = 'Thudufushi Medical Clinic';
UPDATE public.hospitals SET address_dv = 'ތުޅަގިރި އައިލެންޑް' WHERE name = 'Thulhagiri Clinic';
UPDATE public.hospitals SET address_dv = 'ޓައިނީ ޑްރޮޕްސް މެޑިކަލް ސާވިސަސް، މާލެ' WHERE name = 'Tiny Drops Medical Services';
UPDATE public.hospitals SET address_dv = 'ޓޮޓަލްފިޒިއޯ، މާލެ' WHERE name = 'TotalPhysio';
UPDATE public.hospitals SET address_dv = 'ޓްރޫ ކެއަރ މެޑިކަލްސް، މާލެ' WHERE name = 'True Care Medicals';
UPDATE public.hospitals SET address_dv = 'ޓީޓީއެޗް ކްލިނިކް، މާލެ' WHERE name = 'TTH Clinic';
UPDATE public.hospitals SET address_dv = 'ވާދޫ އައިލެންޑް' WHERE name = 'Vadoo Clinic HF -23/ALP/PVT/708';
UPDATE public.hospitals SET address_dv = 'ވަރު މެޑިކަލް ސެންޓަރު، މާލެ' WHERE name = 'Varu Medical Centre';
UPDATE public.hospitals SET address_dv = 'ވީކެއަރ ކައުންސިލިންގ އެންޑް ސައިކޮތެރަޕީ ސެންޓަރު، މާލެ' WHERE name = 'VCare Counselling and Psychotherapy Centre';
UPDATE public.hospitals SET address_dv = 'ވެލާ ޕްރައިވެޓް އައިލެންޑް ކްލިނިކް' WHERE name = 'Velaa Private Island Clinic';
UPDATE public.hospitals SET address_dv = 'ވެލަސްރު މެޑިކަލް ސެންޓަރު، މާލެ' WHERE name = 'Velassaru Medical Center';
UPDATE public.hospitals SET address_dv = 'ވެލިގަނޑު އައިލެންޑް' WHERE name = 'Veligandu Clinic HF -23/ALP/PVT/704';
UPDATE public.hospitals SET address_dv = 'ވެރސޯ މެޑިކަލްސެންޓަރު، އއލ. އަލިފުށި' WHERE name = 'Verso MedicalCentre Alifushi';
UPDATE public.hospitals SET address_dv = 'ވިލާ ބައިޔޯ މެޑިކަލްސް ލެބޯރޭޓްރީ، މާލެ' WHERE name = 'Villa Bio Medicals Laboratory';
UPDATE public.hospitals SET address_dv = 'ވިޔަން ކެއަރ އޮޕްޓިކަލް އެންޑް އައި ކްލިނިކް، މާލެ' WHERE name = 'Vision Care Optical and Eye Clinic';
UPDATE public.hospitals SET address_dv = 'ވިޔަން ކްލިނިކް، މާލެ' WHERE name = 'Vision Clinic';
UPDATE public.hospitals SET address_dv = 'ވިޔަން ކްލިނިކް، ހުޅުމާލެ' WHERE name = 'Vision Clinic Hulhumale''';
UPDATE public.hospitals SET address_dv = 'ވިޔަން ކްލިނިކް-1، މާލެ' WHERE name = 'Vision Clinic-1';
UPDATE public.hospitals SET address_dv = 'ވައިޓަލް ކެއަރ، މާލެ' WHERE name = 'Vital Care';
UPDATE public.hospitals SET address_dv = 'ވައިޓަލް ކެއަރ، ކުޅުދުއްފުށި' WHERE name = 'Vital Care Kulhudhufushi Anex';
UPDATE public.hospitals SET address_dv = 'ވައިޓަލް ކެއަރ، ކުޅުދުއްފުށި' WHERE name = 'Vital Care- Kulhudhuffushi';
UPDATE public.hospitals SET address_dv = 'ވައިޓަލްކެއަރ ޑެންޓަލް، މާލެ' WHERE name = 'VitalCare Dental';
UPDATE public.hospitals SET address_dv = 'ވައިޓަލްކެއަރ، ގއ. ތިނަދޫ' WHERE name = 'Vitalcare Huvadhoo';
UPDATE public.hospitals SET address_dv = 'ވިވާޑެންޓް ޑެންޓަލް ސެންޓަރު، މާލެ' WHERE name = 'Vivadent Dental Center';
UPDATE public.hospitals SET address_dv = 'ވޮމުލި އައިލެންޑް' WHERE name = 'Vommuli Clinic';
UPDATE public.hospitals SET address_dv = 'ވެލްކެއަރ ފިޒިއޮތެރަޕީ އެންޑް ސްޕޯޓްސް ރިހެބިލިޓޭޝަން، މާލެ' WHERE name = 'Wellcare Physiotherapy & Sports Rehabilitation';
UPDATE public.hospitals SET address_dv = 'ޔޫ އެންޑް މީ ކްލިނިކް، މާލެ' WHERE name = 'You & Me Clinic';

COMMIT;
