BEGIN;

UPDATE public.hospitals SET name_dv = 'ފޯ ސީޒަންސް ރިސޯޓް ކުޑަ ހުރާ ކްލިނިކް' WHERE name = 'Four Seasons Resort Kuda Huraa Clinic';
UPDATE public.hospitals SET name_dv = 'ފުރަނާ ކްލިނިކް' WHERE name = 'Furana Clinic';
UPDATE public.hospitals SET name_dv = 'ފުރަވެރި ކްލިނިކް' WHERE name = 'Furaveri Clinic';
UPDATE public.hospitals SET name_dv = 'ގަންގީހި ކްލިނިކް' WHERE name = 'Gangehi Clinic HF - 23/ALP/PVT/706';
UPDATE public.hospitals SET name_dv = 'ގްރޭޓް މައިންޑްސް' WHERE name = 'Great Minds';
UPDATE public.hospitals SET name_dv = 'ގެސްޓް އެންޑް ސްޓާފް ކްލިނިކް' WHERE name = 'Guest and Staff Clinic';
UPDATE public.hospitals SET name_dv = 'ހާޖީ މެޑިކަލް ކްލިނިކް' WHERE name = 'Haajy Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ހަކުރާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Hakuraa Medical Centre';
UPDATE public.hospitals SET name_dv = 'ހަލަވެލި ކްލިނިކް' WHERE name = 'Halaveli Clinic';
UPDATE public.hospitals SET name_dv = 'ހާރޓް ކެއަރ' WHERE name = 'Heart Care';
UPDATE public.hospitals SET name_dv = 'ހެލެންގިރީ ކްލިނިކް' WHERE name = 'Helengeli Clinic';
UPDATE public.hospitals SET name_dv = 'ހޯޕް ހެލްތް ކެއަރ' WHERE name = 'Hope Health Care';
UPDATE public.hospitals SET name_dv = 'ހުދުރަންފުށި ކްލިނިކް' WHERE name = 'Hudhuranfushi Clinic';
UPDATE public.hospitals SET name_dv = 'ހުރަވަޅި ކްލިނިކް' WHERE name = 'Hurawalhi Clinic';
UPDATE public.hospitals SET name_dv = 'ޙުސައިން ޢަބްދުލް ސަމާދު މެމޮރިއަލް ކްލިނިކް' WHERE name = 'Hussain Abdul Samad Memorial Clinic';
UPDATE public.hospitals SET name_dv = 'ހުވަދޫ ތެރަޕީ ކްލިނިކް' WHERE name = 'Huvadhoo Therapy Clinic';
UPDATE public.hospitals SET name_dv = 'ހުވަފެން ފުށި ކްލިނިކް' WHERE name = 'Huvafen Fushi Clinic';
UPDATE public.hospitals SET name_dv = 'އައި ވެއަރ' WHERE name = 'I wear';
UPDATE public.hospitals SET name_dv = 'އައިއެމްޑީސީ މަލްޓި ސްޕެޝަލިޓީ ހޮސްޕިޓަލް' WHERE name = 'I.M.D.C Multi Speciality Hospital';
UPDATE public.hospitals SET name_dv = 'އައިކޭޓީޓީ މޯލްޑިވްސް' WHERE name = 'ICATT Maldives- Medical Services';
UPDATE public.hospitals SET name_dv = 'އިފުރު ކްލިނިކް' WHERE name = 'Ifuru Clinic';
UPDATE public.hospitals SET name_dv = 'އައިއެޗްޖީ މާމުނަގައު ކްލިނިކް' WHERE name = 'IHG Maamunagau Clinic';
UPDATE public.hospitals SET name_dv = 'އިމޭޖް ސެންޓަރު' WHERE name = 'Image Centre';
UPDATE public.hospitals SET name_dv = 'އިމްޕީރިއަލް މެޑިކެއަރ ސެންޓަރު' WHERE name = 'Imperial Medicare Centre';
UPDATE public.hospitals SET name_dv = 'އައިޖީއެމްއެޗް' WHERE name = 'Indira Gandhi Memorial Hospital (IGMH)';
UPDATE public.hospitals SET name_dv = 'އިންސްޓިޓިއުޓް ފޯ ކައުންސިލިންގ އެންޑް ސައިކޮތެރަޕީ' WHERE name = 'Institute For Counselling And Psychotherapy';
UPDATE public.hospitals SET name_dv = 'އިތާފުށި ކްލިނިކް' WHERE name = 'Ithaafushi Clinic';
UPDATE public.hospitals SET name_dv = 'ޖަވަކާރާ ކްލިނިކް' WHERE name = 'Jawakara Clinic';
UPDATE public.hospitals SET name_dv = 'ޖޭޕީ މެމޮރިއަލް ކްލިނިކް' WHERE name = 'JP Memorial Clinic';
UPDATE public.hospitals SET name_dv = 'ކާމް މެޑިކަލް' WHERE name = 'Kaam Medical';
UPDATE public.hospitals SET name_dv = 'ކާގި ކްލިނިކް' WHERE name = 'Kagi Clinic';
UPDATE public.hospitals SET name_dv = 'ކަނދޮޅު ކްލިނިކް' WHERE name = 'Kandolhu Clinic HF -23/ALP/PVT/713';
UPDATE public.hospitals SET name_dv = 'ކަނދޫމާ ކްލިނިކް' WHERE name = 'Kandooma Clinic';
UPDATE public.hospitals SET name_dv = 'ކަނުހުރާ ކްލިނިކް' WHERE name = 'Kanuhura Clinic';
UPDATE public.hospitals SET name_dv = 'ނޯހަބް' WHERE name = 'Knowhub';
UPDATE public.hospitals SET name_dv = 'ކޮމަންޑޫ ކްލިނިކް' WHERE name = 'Komandoo Clinic HF -23/ALP/PVT/712';
UPDATE public.hospitals SET name_dv = 'ކޮތައިފަރު ކްލިނިކް' WHERE name = 'Kothaifaru Clinic';
UPDATE public.hospitals SET name_dv = 'ކުޑަ ވިލިންގިލި' WHERE name = 'Kuda Villingili';
UPDATE public.hospitals SET name_dv = 'ކުޅުޙެލަމާ ތެރަޕީ' WHERE name = 'Kulhelama Therapy';
UPDATE public.hospitals SET name_dv = 'ކުޅުނު މެޑިކަލް ކްލިނިކް' WHERE name = 'Kulunu Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ކުނާވަޝި ކްލިނިކް' WHERE name = 'Kunaavashi Clinic';
UPDATE public.hospitals SET name_dv = 'ކުރަމަތި މެޑިކަލް ސެންޓަރު' WHERE name = 'Kuramathi Medical Centre';
UPDATE public.hospitals SET name_dv = 'ކުރެދިވަރު ކްލިނިކް' WHERE name = 'kuredivaru Clinic';
UPDATE public.hospitals SET name_dv = 'ކުރުންބާ ކްލިނިކް' WHERE name = 'Kurumba Clinic';
UPDATE public.hospitals SET name_dv = 'ލޭބް މޯލްޑިވްސް' WHERE name = 'Lab Maldives';
UPDATE public.hospitals SET name_dv = 'ލީފް އޮފް ލައިފް ކްލިނިކް' WHERE name = 'Leaf of Life Clinic';
UPDATE public.hospitals SET name_dv = 'ލޭކޮކާ މެޑިކަލް އެންޑް ރިހެބިލިޓޭޝަން ސެންޓަރު' WHERE name = 'Leykokaa Medical and Rehabilitation Centre';
UPDATE public.hospitals SET name_dv = 'ލައިފް ކެއަރ މެޑިކަލް ސެންޓަރު' WHERE name = 'Life Care Medical Centre';
UPDATE public.hospitals SET name_dv = 'ލައިފް ވެލްނެސް ކްލިނިކް' WHERE name = 'Life Wellness Clinic';
UPDATE public.hospitals SET name_dv = 'ލަކްސް މޯލްޑިވްސް ރިސޯޓް ކްލިނިކް' WHERE name = 'Lux Maldives Resort Clinic';
UPDATE public.hospitals SET name_dv = 'މާދޫ ކްލިނިކް' WHERE name = 'Maadhoo Clinic';
UPDATE public.hospitals SET name_dv = 'މާފުށިވަރު ކްލިނިކް' WHERE name = 'Maafushivaru Clinic';
UPDATE public.hospitals SET name_dv = 'މާމިގިލި ކްލިނިކް' WHERE name = 'Maamigili Clinic';
UPDATE public.hospitals SET name_dv = 'މާންދޫ މެޑިކަލް ސެންޓަރު' WHERE name = 'Maandhoo Medical Centre';
UPDATE public.hospitals SET name_dv = 'މާޔަފުށި ކްލިނިކް' WHERE name = 'Maayafushi Clinic';
UPDATE public.hospitals SET name_dv = 'މެކް މެޑިކަލް ކްލިނިކް' WHERE name = 'MACL Medical Clinic';
UPDATE public.hospitals SET name_dv = 'މަފްހާ ޑައިގްނޮސްޓިކް ސެންޓަރު' WHERE name = 'Mafhaa Diagnostic Centre';
UPDATE public.hospitals SET name_dv = 'މަގޭ ފިޒިއޯ' WHERE name = 'Magey Physio';
UPDATE public.hospitals SET name_dv = 'މޯލްޑިވްސް އަލްޓަނޭޓިވް މެޑިކަލް ސެންޓަރު' WHERE name = 'Maldives Alternative Medical Centre';
UPDATE public.hospitals SET name_dv = 'މޯލްޑިވްސް ނިއުރޯ އެންޑޮކްރައިން މެޑިކަލް ފެސިލިޓީ' WHERE name = 'Maldives Neuro Endocrine Medical Facility';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް ޑެންޓަލް ކެއަރ ސެންޓަރު' WHERE name = 'Master Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް ޑެންޓަލް ކެއަރ ސެންޓްރޯ' WHERE name = 'Master Dental Care Centro';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް މެޑިކަލް އެންޑް ޑެންޓަލް ކެއަރ ސެންޓަރު' WHERE name = 'Master Medical and Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'މެޑްހޯޕް މެޑިކަލް ސެންޓަރު' WHERE name = 'Medhope Medical Centre';
UPDATE public.hospitals SET name_dv = 'މެޑިކާ' WHERE name = 'Medica';
UPDATE public.hospitals SET name_dv = 'މެޑިކާ އެނެކްސް' WHERE name = 'Medica Annex';
UPDATE public.hospitals SET name_dv = 'މެޑިކަލް އެންޑް ހައިޕަރބާރިކް ކްލިނިކް' WHERE name = 'Medical & Hyperbaric Clinic';
UPDATE public.hospitals SET name_dv = 'މެޑިކްރެސްޓް ކްލިނިކް އެންޑް ޑައިގްނޮސްޓިކްސް' WHERE name = 'Medicrest Clinic and Diagnostics';
UPDATE public.hospitals SET name_dv = 'މެޑިފްލެކްސް ޑެންޓަލް އެންޑް މެކްސިލޮފޭޝަލް ސާޖަރީ' WHERE name = 'Mediflex Dental and Maxillofacial Surgery';
UPDATE public.hospitals SET name_dv = 'މެޑްނޮވާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Mednova Medical Center';
UPDATE public.hospitals SET name_dv = 'މީދުއްޕަރު ކްލިނިކް' WHERE name = 'Meedhupparu Clinic';
UPDATE public.hospitals SET name_dv = 'މީރު ކްލިނިކް' WHERE name = 'Meeru Clinic';
UPDATE public.hospitals SET name_dv = 'މިލައިދޫ ކްލިނިކް' WHERE name = 'Milaidhoo Clinic';
UPDATE public.hospitals SET name_dv = 'މައިންޑް ސްޕޭސް' WHERE name = 'Mind Space';
UPDATE public.hospitals SET name_dv = 'މައިންޑް ކެއަރ ކްލިނިކް' WHERE name = 'Mindcare Clinic';
UPDATE public.hospitals SET name_dv = 'މިޕްސްޓާރ' WHERE name = 'MIPSTAR';
UPDATE public.hospitals SET name_dv = 'މިރިޔަންދޫ މެޑިކަލް ސާވިސަސް' WHERE name = 'Miriandhoo Medical Services';
UPDATE public.hospitals SET name_dv = 'މޫވިންގް ކިޔުރު' WHERE name = 'Moving Cure';
UPDATE public.hospitals SET name_dv = 'އެމްޕީއައި ކްލިނިކް' WHERE name = 'MPI Clinique';
UPDATE public.hospitals SET name_dv = 'މުއްދޫ ކްލިނިކް' WHERE name = 'Mudhdhoo Clinic';
UPDATE public.hospitals SET name_dv = 'މުރަކާ ކްލިނިކް' WHERE name = 'Muraka Clinic';
UPDATE public.hospitals SET name_dv = 'މައި ކްލިނިކް' WHERE name = 'My Clinic';
UPDATE public.hospitals SET name_dv = 'މައި ޑެންޓަލް ކެއަރ' WHERE name = 'My Dental Care HF -23/ALP/PVT/710';
UPDATE public.hospitals SET name_dv = 'މައި ފެމިލީ ޑެންޓިސްޓް' WHERE name = 'My Family Dentist';
UPDATE public.hospitals SET name_dv = 'މައި ފެމިލީ ޑެންޓިސްޓް މާލެ' WHERE name = 'My Family Dentist Male''';
UPDATE public.hospitals SET name_dv = 'ނަފްސު ސައިކޮލޮޖިކަލް ސާވިސަސް' WHERE name = 'Nafsu Psychological Services';
UPDATE public.hospitals SET name_dv = 'ނައިފަރު މެޑިކަލް ސެންޓަރު' WHERE name = 'Naifaru Medical Center';
UPDATE public.hospitals SET name_dv = 'ނަޒާ ހެލްތް' WHERE name = 'NazaHealth';
UPDATE public.hospitals SET name_dv = 'ނިޔަމާ ރިސޯޓް ކްލިނިކް' WHERE name = 'Niyama Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ނޫ ކްލިނިކް' WHERE name = 'Noo Clinic';
UPDATE public.hospitals SET name_dv = 'ނޫސަންދާ' WHERE name = 'Noosandha';
UPDATE public.hospitals SET name_dv = 'ނޫސަންދާ - އައްޑު' WHERE name = 'Noosandha - Addu';
UPDATE public.hospitals SET name_dv = 'ނޮވާ ކްލިނިކް' WHERE name = 'Nova Clinic';
UPDATE public.hospitals SET name_dv = 'ނޯވޯލް މެޑިކަލް ސެންޓަރު' WHERE name = 'Nowall Medical Centre';
UPDATE public.hospitals SET name_dv = 'އޯގާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Oagaa Medical Centre';
UPDATE public.hospitals SET name_dv = 'އޮޅުހަޅި ކްލިނިކް' WHERE name = 'Olhahali Clinic';
UPDATE public.hospitals SET name_dv = 'އޮމެގާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Omega Medical Centre';
UPDATE public.hospitals SET name_dv = 'އައުޗް' WHERE name = 'Ouch';
UPDATE public.hospitals SET name_dv = 'ޕެއިން ކްލިނިކް' WHERE name = 'Pain Clinic';
UPDATE public.hospitals SET name_dv = 'ޕާރލް މެޑިކަލް ސެންޓަރު' WHERE name = 'Pearl Medical Centre';
UPDATE public.hospitals SET name_dv = 'ޕާރލް މެޑިކަލް ސެންޓަރު ހުޅުމާލެ' WHERE name = 'Pearl Medical Centre Hulhumale';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ އެންޑް އޮޓިޒަމް ކްލިނިކް' WHERE name = 'Physio & Autism Clinic - Hulhumale''';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ އެންޑް އޮޓިޒަމް ކްލިނިކް' WHERE name = 'Physio and Autism Clinic';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކްލިނިކް' WHERE name = 'Physio Clinic';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކްލިނިކް އެނެކްސް 1' WHERE name = 'Physio Clinic Annex 1';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކިޔުރު' WHERE name = 'Physio Cure';
UPDATE public.hospitals SET name_dv = 'ޕައިން ޓްރީ މެޑިކް ކެއަރ' WHERE name = 'Pine tree Medic Care';
UPDATE public.hospitals SET name_dv = 'ޕޮޕިޔުލާ ކްލިނިކް' WHERE name = 'Popular Clinic';
UPDATE public.hospitals SET name_dv = 'ޕްރޯ ކެއަރ ކްލިނިކް އެންޑް ޑެންޓަލް ސެންޓަރު' WHERE name = 'Pro Care Clinic and Dental Centre';
UPDATE public.hospitals SET name_dv = 'ޕުލްމަން މޯލްޑިވްސް މާމުތާ ރިސޯޓް ކްލިނިކް' WHERE name = 'Pullman Maldives Maamutaa Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ކުއީން އެސްތެޓިކް މެޑިކަލް ސެންޓަރު' WHERE name = 'Queen Aesthetic Medical Center';
UPDATE public.hospitals SET name_dv = 'ރާޔާ ކްލިނިކް' WHERE name = 'Raaya Clinic';
UPDATE public.hospitals SET name_dv = 'ރެފްލްސް ކްލިނިކް' WHERE name = 'Raffles Clinic';
UPDATE public.hospitals SET name_dv = 'ރަންގާލި ކްލިނިކް' WHERE name = 'Rangali Clinic';
UPDATE public.hospitals SET name_dv = 'ރަންނާލި ކްލިނިކް' WHERE name = 'Rannalhi Clinic HF22/ALP/PVT/659';
UPDATE public.hospitals SET name_dv = 'ރަސްފުށި ކްލިނިކް' WHERE name = 'Rasfushi Clinic';
UPDATE public.hospitals SET name_dv = 'ރީތި ބީޗް ކްލިނިކް' WHERE name = 'Reethi Beach Clilnic HF -23/ALP/PVT/711';
UPDATE public.hospitals SET name_dv = 'ރީތި ފަރު ކްލިނިކް' WHERE name = 'Reethi Faru Clinic';
UPDATE public.hospitals SET name_dv = 'ރިސޯޓް ކްލިނިކް' WHERE name = 'Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ރިސޯޓް މެޑިކަލް އެންޑް ލެބޮރޭޓްރީ ސާވިސަސް' WHERE name = 'Resort Medical and Laboratory Services';
UPDATE public.hospitals SET name_dv = 'ރިވައިވް މެޑިކަލް ސެންޓަރު' WHERE name = 'Revive Medical Centre';
UPDATE public.hospitals SET name_dv = 'އާރއެމްއެލް އެސް ލެބް ސާވިސަސް' WHERE name = 'RMLS Lab Services';
UPDATE public.hospitals SET name_dv = 'ރުގަލު ކްލިނިކް' WHERE name = 'Ruhgalu Clinic';
UPDATE public.hospitals SET name_dv = 'އާރއެކްސް މެޑިކެއަރ' WHERE name = 'Rx Medicare';
UPDATE public.hospitals SET name_dv = 'ސަންޑީސް ބަތަލާ އިންފަރމަރީ' WHERE name = 'Sandies Bathala Infirmary';
UPDATE public.hospitals SET name_dv = 'ޝާ ތެރަޕީ ދިވެހިބޭސް ސެންޓަރު' WHERE name = 'Sha Therapy Dhivehibeys Centre';
UPDATE public.hospitals SET name_dv = 'ޝިފާ މެޑިކަލް' WHERE name = 'Shifaa Medical';
UPDATE public.hospitals SET name_dv = 'ސިކްސް ސެންސިސް ލާމު ކްލިނިކް' WHERE name = 'Six Sensus Laamu Clinic';
UPDATE public.hospitals SET name_dv = 'ސިޔާމް ވޯރްލްޑް މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Siyam World Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސްމައިލްސް ޑެންޓަލް ކެއަރ' WHERE name = 'Smiles Dental Care';
UPDATE public.hospitals SET name_dv = 'ސްމައިލްސް ޑެންޓަލް ކެއަރ ހުޅުމާލެ' WHERE name = 'Smiles Dental Care Hulhumale''';
UPDATE public.hospitals SET name_dv = 'އެސްއޯ މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'SO/ Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސޮނެވާ ފުށި ކްލިނިކް' WHERE name = 'Soneva Fushi Clinic';
UPDATE public.hospitals SET name_dv = 'ސޮނެވާ ޖާނި ކްލިނިކް' WHERE name = 'Soneva Jani Clinic';
UPDATE public.hospitals SET name_dv = 'ސައުތަން ކެއަރ ކްލިނިކް' WHERE name = 'Southern Care Clinic';
UPDATE public.hospitals SET name_dv = 'ސްޓާރް މެޑިކަލް' WHERE name = 'Star Medical';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް އިރުފުށި މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Sun Siyam Irufushi Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް އިރުވެލި މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Sun Siyam Iruveli Maldives Clinic HF -23/ALP/PVT/709';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް އޮޅުވެލި މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Sun Siyam Olhuveli Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް ވިލު ރީފް މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Sun Siyam Vilu Reef Maldives CLinic';
UPDATE public.hospitals SET name_dv = 'ސިނަރްޖީ ކެއަރ' WHERE name = 'Synergy Care';
UPDATE public.hospitals SET name_dv = 'ތާޖް އެކްޒޮޓިކާ ކްލިނިކް' WHERE name = 'Taj Exotica Clinic';
UPDATE public.hospitals SET name_dv = 'ދަ ރެޒިޑެންސް މޯލްޑިވްސް އެޓް ދިގުރާ ކްލިނިކް' WHERE name = 'The Residence Maldives at Dhigurah Clinic';
UPDATE public.hospitals SET name_dv = 'ދަ ސްޓެންޑާޑް ކްލިނިކް' WHERE name = 'The Standard Clinic';
UPDATE public.hospitals SET name_dv = 'ތެރަޕީ ސެންޓަރު' WHERE name = 'Therapy Centre';
UPDATE public.hospitals SET name_dv = 'ތިލަމާފުށި ކްލިނިކް' WHERE name = 'Thilamaafushi Clinic';
UPDATE public.hospitals SET name_dv = 'ތުނޑުފުށި މެޑިކަލް ކްލިނިކް' WHERE name = 'Thudufushi Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ތުޅަގިރި ކްލިނިކް' WHERE name = 'Thulhagiri Clinic';
UPDATE public.hospitals SET name_dv = 'ޓައިނީ ޑްރޮޕްސް މެޑިކަލް ސާވިސަސް' WHERE name = 'Tiny Drops Medical Services';
UPDATE public.hospitals SET name_dv = 'ޓޮޓަލްފިޒިއޯ' WHERE name = 'TotalPhysio';
UPDATE public.hospitals SET name_dv = 'ޓްރޫ ކެއަރ މެޑިކަލްސް' WHERE name = 'True Care Medicals';
UPDATE public.hospitals SET name_dv = 'ޓީޓީއެޗް ކްލިނިކް' WHERE name = 'TTH Clinic';
UPDATE public.hospitals SET name_dv = 'ވާދޫ ކްލިނިކް' WHERE name = 'Vadoo Clinic HF -23/ALP/PVT/708';
UPDATE public.hospitals SET name_dv = 'ވަރު މެޑިކަލް ސެންޓަރު' WHERE name = 'Varu Medical Centre';
UPDATE public.hospitals SET name_dv = 'ވީކެއަރ ކައުންސިލިންގ އެންޑް ސައިކޮތެރަޕީ ސެންޓަރު' WHERE name = 'VCare Counselling and Psychotherapy Centre';
UPDATE public.hospitals SET name_dv = 'ވެލާ ޕްރައިވެޓް އައިލެންޑް ކްލިނިކް' WHERE name = 'Velaa Private Island Clinic';
UPDATE public.hospitals SET name_dv = 'ވެލަސްރު މެޑިކަލް ސެންޓަރު' WHERE name = 'Velassaru Medical Center';
UPDATE public.hospitals SET name_dv = 'ވެލިގަނޑު ކްލިނިކް' WHERE name = 'Veligandu Clinic HF -23/ALP/PVT/704';
UPDATE public.hospitals SET name_dv = 'ވެރސޯ މެޑިކަލްސެންޓަރު އަލިފުށި' WHERE name = 'Verso MedicalCentre Alifushi';
UPDATE public.hospitals SET name_dv = 'ވިލާ ބައިޔޯ މެޑިކަލްސް ލެބޯރޭޓްރީ' WHERE name = 'Villa Bio Medicals Laboratory';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކެއަރ އޮޕްޓިކަލް އެންޑް އައި ކްލިނިކް' WHERE name = 'Vision Care Optical and Eye Clinic';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް' WHERE name = 'Vision Clinic';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް ހުޅުމާލެ' WHERE name = 'Vision Clinic Hulhumale''';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް-1' WHERE name = 'Vision Clinic-1';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ' WHERE name = 'Vital Care';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ ކުޅުދުއްފުށި އެނެކްސް' WHERE name = 'Vital Care Kulhudhufushi Anex';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ- ކުޅުދުއްފުށި' WHERE name = 'Vital Care- Kulhudhuffushi';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލްކެއަރ ޑެންޓަލް' WHERE name = 'VitalCare Dental';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލްކެއަރ ހުވަދޫ' WHERE name = 'Vitalcare Huvadhoo';
UPDATE public.hospitals SET name_dv = 'ވިވާޑެންޓް ޑެންޓަލް ސެންޓަރު' WHERE name = 'Vivadent Dental Center';
UPDATE public.hospitals SET name_dv = 'ވޮމުލި ކްލިނިކް' WHERE name = 'Vommuli Clinic';
UPDATE public.hospitals SET name_dv = 'ވެލްކެއަރ ފިޒިއޮތެރަޕީ އެންޑް ސްޕޯޓްސް ރިހެބިލިޓޭޝަން' WHERE name = 'Wellcare Physiotherapy & Sports Rehabilitation';
UPDATE public.hospitals SET name_dv = 'ޔޫ އެންޑް މީ ކްލިނިކް' WHERE name = 'You & Me Clinic';

COMMIT;
