-- UPDATE: Dhivehi addresses for 174 hospitals
-- Part 1: First 100 hospitals

BEGIN;

UPDATE public.hospitals SET address_dv = 'އޯގާ އާޓް ރިސޯޓްސް، ކ. މާރަންފުށި' WHERE name = 'ADK Hospital Reach Clinic, Maaranfushi';
UPDATE public.hospitals SET address_dv = 'ހުޅުމާލެ ލޮޓް 11123، ރޯ ހައުސް 13-08، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Alai Play and Learn Therapy Center HF - 23/ALP/PVT/705';
UPDATE public.hospitals SET address_dv = 'މިރިހާނާ، ސ. މީދޫ' WHERE name = 'F&C Medicare, Meedhoo';
UPDATE public.hospitals SET address_dv = 'ފޯ ސީޒަންސް ރިސޯޓް މޯލްޑިވްސް އެޓް ކުޑަހުރާ، މޯލްޑިވްސް' WHERE name = 'Four Seasons Resort Kuda Huraa Clinic';
UPDATE public.hospitals SET address_dv = 'ފުރަނާފުށި އައިލެންޑް، ނޯތް މާލެ އަތޮޅު' WHERE name = 'Furana Clinic';
UPDATE public.hospitals SET address_dv = 'ފުރަވެރި ރިސޯޓް މޯލްޑިވްސް' WHERE name = 'Furaveri Clinic';
UPDATE public.hospitals SET address_dv = 'ގަންގީހި އައިލެންޑް ރިސޯޓް، އއ. ގަންގީހި، މޯލްޑިވްސް' WHERE name = 'Gangehi Clinic HF - 23/ALP/PVT/706';
UPDATE public.hospitals SET address_dv = 'ވަވަތި ބިލްޑިންގ، 2އޭ، މާލެ، މޯލްޑިވްސް' WHERE name = 'Great Minds';
UPDATE public.hospitals SET address_dv = 'ގދ. ކޮނޮއްޓާ، ގދ. އަތޮޅު، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Guest and Staff Clinic';
UPDATE public.hospitals SET address_dv = 'ސައުތް ވާރޑް، ހިކިފިނިފެންމާގެ، ހދ. ކުޅުދުއްފުށި' WHERE name = 'Haajy Medical Clinic';
UPDATE public.hospitals SET address_dv = '' WHERE name = 'Hakuraa Medical Centre';
UPDATE public.hospitals SET address_dv = 'ކޮންސްޓޭންސް ހަލަވެލި ރިސޯޓް، ނޯތް އަރި އަތޮޅު' WHERE name = 'Halaveli Clinic';
UPDATE public.hospitals SET address_dv = 'ގ. އަލިދޫގެ، ކ. މާލެ' WHERE name = 'Heart Care';
UPDATE public.hospitals SET address_dv = 'އޮބްލޫ އެޓްމޮސްފީއަރ އެޓް ހެލެންގިރީ، ހެލެންގިރީ، ކ. މާލެ' WHERE name = 'Helengeli Clinic';
UPDATE public.hospitals SET address_dv = '101، ހ. ބުރުނީގެ ދެކުނުގެ، ކ. މާލެ' WHERE name = 'Hope Health Care';
UPDATE public.hospitals SET address_dv = 'އަޑާރާން ސެލެކްޓް ހުދުރަންފުށި، ކ. ޅޮހިފުށި' WHERE name = 'Hudhuranfushi Clinic';
UPDATE public.hospitals SET address_dv = 'ހުރަވަޅި އައިލެންޑް ރިސޯޓް، ޅ. ހުރަވަޅި، މޯލްޑިވްސް' WHERE name = 'Hurawalhi Clinic';
UPDATE public.hospitals SET address_dv = 'މާޔާ، އއދ. ދަންގެތި، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Hussain Abdul Samad Memorial Clinic';
UPDATE public.hospitals SET address_dv = 'ކޭވަކުގެ، ގދ. ތިނަދޫ' WHERE name = 'Huvadhoo Therapy Clinic';
UPDATE public.hospitals SET address_dv = 'ހުވަފެންފުށި، ނޯތް މާލެ އަތޮޅު، މޯލްޑިވްސް' WHERE name = 'Huvafen Fushi Clinic';
UPDATE public.hospitals SET address_dv = 'މ. ބްލޫ ޗިޕް، އޯކިޑް މަގު، މާލެ، މޯލްޑިވްސް' WHERE name = 'I wear';
UPDATE public.hospitals SET address_dv = 'އަލްބަނީ، ސ. ހިތަދޫ' WHERE name = 'I.M.D.C Multi Speciality Hospital';
UPDATE public.hospitals SET address_dv = '5ސީ، 5ވަނަ ފްލޯރް، ސަކައިމޫ ބިލްޑިންގ، ހަވީރީ ހިނގުން، މާލެ' WHERE name = 'ICATT Maldives- Medical Services';
UPDATE public.hospitals SET address_dv = 'އިފުރު އައިލެންޑް، ރ. އަތޮޅު' WHERE name = 'Ifuru Clinic';
UPDATE public.hospitals SET address_dv = 'މާމުނަގައު އައިލެންޑް، ރ. އަތޮޅު' WHERE name = 'IHG Maamunagau Clinic';
UPDATE public.hospitals SET address_dv = 'ހ. ޝޭޑީ ޕާލްމް، ހިތަފިނިވާ މަގު، މާލެ' WHERE name = 'Image Centre';
UPDATE public.hospitals SET address_dv = 'ގ. ޗަމަން، ކ.މާލެ' WHERE name = 'Imperial Medicare Centre';
UPDATE public.hospitals SET address_dv = 'ބޮދުތަކުރުފާނު މަގު، މާލެ' WHERE name = 'Indira Gandhi Memorial Hospital (IGMH)';
UPDATE public.hospitals SET address_dv = 'ހ.ހައިފާ، ބޮދުފެނަވަޅިގެ މަގު، މާލެ' WHERE name = 'Institute For Counselling And Psychotherapy';
UPDATE public.hospitals SET address_dv = 'އިތާފުށި، މާލެ އަތޮޅު' WHERE name = 'Ithaafushi Clinic';
UPDATE public.hospitals SET address_dv = 'މަބިންހުރަ އައިލެންޑް، ޅަވިޔަނީ އަތޮޅު، މޯލްޑިވްސް' WHERE name = 'Jawakara Clinic';
UPDATE public.hospitals SET address_dv = 'ރޮބިންސަން މޯލްޑިވްސް، ގއ. ފުނައިމައުއްދާ، ހުވަދޫ އަތޮޅު' WHERE name = 'JP Memorial Clinic';
UPDATE public.hospitals SET address_dv = 'ލޮޓް 10414، އަހިގާސް މަގު، ހުޅުމާލެ' WHERE name = 'Kaam Medical';
UPDATE public.hospitals SET address_dv = 'ކާގި މޯލްޑިވްސް ސްޕާ އައިލެންޑް' WHERE name = 'Kagi Clinic';
UPDATE public.hospitals SET address_dv = 'އއ. ކަނދޮޅުދޫ' WHERE name = 'Kandolhu Clinic HF -23/ALP/PVT/713';
UPDATE public.hospitals SET address_dv = 'ހޮލިޑޭ އިން ރިސޯޓް ކަނދޫމާ' WHERE name = 'Kandooma Clinic';
UPDATE public.hospitals SET address_dv = 'ކަނުހުރާ، ޅަވިޔާނީ' WHERE name = 'Kanuhura Clinic';
UPDATE public.hospitals SET address_dv = 'ގ. ހިޔާކުރި، އަލިކިލެގެފާނު މަގު، މާލެ' WHERE name = 'Knowhub';
UPDATE public.hospitals SET address_dv = 'ކޮމަންޑޫ މޯލްޑިވްސް އައިލެންޑް ރިސޯޓް' WHERE name = 'Komandoo Clinic HF -23/ALP/PVT/712';
UPDATE public.hospitals SET address_dv = 'އަލިލާ ކޮތައިފަރު މޯލްޑިވްސް، ރ. އަތޮޅު' WHERE name = 'Kothaifaru Clinic';
UPDATE public.hospitals SET address_dv = 'ކުޑަ ވިލިންގިލި ރިސޯޓް' WHERE name = 'Kuda Villingili';
UPDATE public.hospitals SET address_dv = 'މ. ކުޅުނުވެހި 6އޭ، ބުރުޒު މަގު' WHERE name = 'Kulhelama Therapy';
UPDATE public.hospitals SET address_dv = 'މ. ނާރިގުގަސްދޮށުގެ، ކ.މާލެ' WHERE name = 'Kulunu Medical Clinic';
UPDATE public.hospitals SET address_dv = 'ނޫއް މޯލްޑިވްސް ކުނާވަޝި، ވައްވު އަތޮޅު' WHERE name = 'Kunaavashi Clinic';
UPDATE public.hospitals SET address_dv = 'ކުރަމަތި ޓޫރިސްޓް ރިސޯޓް، އަރި އަތޮޅު' WHERE name = 'Kuramathi Medical Centre';
UPDATE public.hospitals SET address_dv = 'މޮވެންޕިކް މާމުނަގައު ރިސޯޓް، ނޫނު އަތޮޅު، މޯލްޑިވްސް' WHERE name = 'kuredivaru Clinic';
UPDATE public.hospitals SET address_dv = 'ކުރުންބާ މޯލްޑިވްސް، ކ. ވިހަމަނާފުށި، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Kurumba Clinic';
UPDATE public.hospitals SET address_dv = 'ލޮޓް ނަންބަރު 11261، ކ. ހުޅުމާލެ، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Lab Maldives';
UPDATE public.hospitals SET address_dv = 'އެންތޫރިއަމް، ހަ. ކެލާ' WHERE name = 'Leaf of Life Clinic';
UPDATE public.hospitals SET address_dv = 'ހ. މީރުބަހުރުގެ' WHERE name = 'Leykokaa Medical and Rehabilitation Centre';
UPDATE public.hospitals SET address_dv = 'ރަބަރުގަސް މަގު 9، ލޮޓް ނަންބަރު 11382' WHERE name = 'Life Care Medical Centre';
UPDATE public.hospitals SET address_dv = 'ހިޔާ ފްލެޓް، އެޗް-5، ޖީ-2، 2300، ހުޅުމާލެ' WHERE name = 'Life Wellness Clinic';
UPDATE public.hospitals SET address_dv = 'އއ. ދިއްދޫފިނޮޅު' WHERE name = 'Lux Maldives Resort Clinic';
UPDATE public.hospitals SET address_dv = 'އޮޒެން ބައި އެޓްމޮސްފީއަރ އެޓް މާދޫ، ކ. މާދޫ، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Maadhoo Clinic';
UPDATE public.hospitals SET address_dv = '' WHERE name = 'Maafushivaru Clinic';
UPDATE public.hospitals SET address_dv = 'ރ. މާމިގިލި، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Maamigili Clinic';
UPDATE public.hospitals SET address_dv = 'ބިލްޑިންގ، ޅ. މާންދޫ' WHERE name = 'Maandhoo Medical Centre';
UPDATE public.hospitals SET address_dv = 'މާޔަފުށި ޓޫރިސްޓް ރިސޯޓް، އއ. މާޔަފުށި، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Maayafushi Clinic';
UPDATE public.hospitals SET address_dv = 'ވެލާނަ އިންޓަރނޭޝަނަލް އެއާރޕޯޓް' WHERE name = 'MACL Medical Clinic';
UPDATE public.hospitals SET address_dv = 'މާލެ ގްރާންޑް، މެޒަނީން ފްލޯރް، ވޭސައިޑްކޮމް 204 އަދި 205' WHERE name = 'Mafhaa Diagnostic Centre';
UPDATE public.hospitals SET address_dv = 'ނައިން ހައުސް، 8ވަނަ ފްލޯރު' WHERE name = 'Magey Physio';
UPDATE public.hospitals SET address_dv = 'މ. އަލުވިމާގެ އާގެ، ނެދުން ގޯޅި، ކ. މާލެ' WHERE name = 'Maldives Alternative Medical Centre';
UPDATE public.hospitals SET address_dv = 'ގ. މާޖެހި އެނެކްސް، ކ. މާލެ' WHERE name = 'Maldives Neuro Endocrine Medical Facility';
UPDATE public.hospitals SET address_dv = 'ގ. ކުދިތިޔަރާ، މާލެ، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Master Dental Care Centre';
UPDATE public.hospitals SET address_dv = 'ސެންޓްރޯ މިނީ ހޯލް، ހުޅުމާލެ، މޯލްޑިވްސް' WHERE name = 'Master Dental Care Centro';
UPDATE public.hospitals SET address_dv = 'ޖިހާދް، ގދ. ގަދޫ' WHERE name = 'Master Medical and Dental Care Centre';
UPDATE public.hospitals SET address_dv = 'މާ. ޕިންނަކަލް، ޗާންދަނީ މަގު، މާލެ، މޯލްޑިވްސް' WHERE name = 'Medhope Medical Centre';
UPDATE public.hospitals SET address_dv = '1، 2، 3، 4 އަދި 5 ވަނަ ފްލޯރު، މ. ދަހަނާ، ފަރީދީ މަގު، ކ. މާލެ' WHERE name = 'Medica';
UPDATE public.hospitals SET address_dv = 'ދާފް ސްޓޯރު ނަންބަރު 1، ފާމުދޭރީ މަގު، މާފަންނު، މާލެ' WHERE name = 'Medica Annex';
UPDATE public.hospitals SET address_dv = 'ކުރެދު އައިލެންޑް، ޅަވިޔާނީ އަތޮޅު' WHERE name = 'Medical & Hyperbaric Clinic';
UPDATE public.hospitals SET address_dv = 'ދޫދާރީ އިމާރާއިއްޔާ، ނ. ވެލިދޫ' WHERE name = 'Medicrest Clinic and Diagnostics';
UPDATE public.hospitals SET address_dv = 'މ. މާޔާ، ގަންދަކޮލި މަގު، މާލެ' WHERE name = 'Mediflex Dental and Maxillofacial Surgery';
UPDATE public.hospitals SET address_dv = 'މ. އާދިލީލީގެ، މާލެ' WHERE name = 'Mednova Medical Center';
UPDATE public.hospitals SET address_dv = 'ރ. މީދުއްޕަރު' WHERE name = 'Meedhupparu Clinic';
UPDATE public.hospitals SET address_dv = 'މީރު އައިލެންޑް ރިސޯޓް އެންޑް ސްޕާ' WHERE name = 'Meeru Clinic';
UPDATE public.hospitals SET address_dv = 'މިލައިދޫ އައިލެންޑް ރިސޯޓް' WHERE name = 'Milaidhoo Clinic';
UPDATE public.hospitals SET address_dv = 'މ. ލޯޖް، ކ. މާލެ' WHERE name = 'Mind Space';
UPDATE public.hospitals SET address_dv = 'ހ. މީދޫ، ފިނިހިޔާ ގޯޅި، މާލެ' WHERE name = 'Mindcare Clinic';
UPDATE public.hospitals SET address_dv = 'މ.އޭ ކިނާރާ ހައުސް' WHERE name = 'MIPSTAR';
UPDATE public.hospitals SET address_dv = 'މިރިޔަންދޫ އައިލެންޑް، ބ. އަތޮޅު' WHERE name = 'Miriandhoo Medical Services';
UPDATE public.hospitals SET address_dv = 'ހ. ބަނޑޮސްގެ، ދުންބުގަސް މަގު، މާލެ' WHERE name = 'Moving Cure';
UPDATE public.hospitals SET address_dv = 'މަދިފުށި ޕްރައިވެޓް އައިލެންޑް، މީމު މަދިފުށި، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'MPI Clinique';
UPDATE public.hospitals SET address_dv = 'ބ. މުއްދޫ އައިލެންޑް، މާލެ' WHERE name = 'Mudhdhoo Clinic';
UPDATE public.hospitals SET address_dv = 'ޖޭވުއްބަރިއަން މޯލްޑިވްސް ކ. އަތޮޅު އައިލެންޑް ރިސޯޓް' WHERE name = 'Muraka Clinic';
UPDATE public.hospitals SET address_dv = 'މާ. މިލާނޯ، ގްރައުންޑް ފްލޯރު، ކ.މާލެ، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'My Clinic';
UPDATE public.hospitals SET address_dv = 'މާމިގިލި ކައުންސިލް 2 ނަންބަރު ފިހާރާ' WHERE name = 'My Dental Care HF -23/ALP/PVT/710';
UPDATE public.hospitals SET address_dv = 'ޔުނިޓް އެޗް3-ޖީ-10، ހިޔާ ހުޅުމާލެ، މާލެ' WHERE name = 'My Family Dentist';
UPDATE public.hospitals SET address_dv = 'ހ. ގްލިސްޓަރު، 1ވަނަ ފްލޯރު، އަބަދަހަތެ ފެހި މަގު، 20081، ކ.މާލެ' WHERE name = 'My Family Dentist Male''';
UPDATE public.hospitals SET address_dv = '' WHERE name = 'Nafsu Psychological Services';
UPDATE public.hospitals SET address_dv = 'ވައިޓް ބިލްޑިންގ، ޅ. ނައިފަރު' WHERE name = 'Naifaru Medical Center';
UPDATE public.hospitals SET address_dv = 'ރޯޒް ގާރްޑަން، ޅ. ނައިފަރު' WHERE name = 'NazaHealth';
UPDATE public.hospitals SET address_dv = 'ނިޔަމާ މޯލްޑިވްސް، ދ. އޮޅުވެލި އަދި އެންބޫދޫ' WHERE name = 'Niyama Resort Clinic';
UPDATE public.hospitals SET address_dv = 'ރޮބިންސަން ނޫނު، ނ.އޮރިވަރު، ނ.އަތޮޅު، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Noo Clinic';
UPDATE public.hospitals SET address_dv = 'މ. އިސްކަންދަރު ކޮށި، ކ.މާލެ، ރިޕަބްލިކް އޮފް މޯލްޑިވްސް' WHERE name = 'Noosandha';
UPDATE public.hospitals SET address_dv = 'ނޭޝަނަލް ކޮލެޖް އޮފް ޕޮލިސިންގ އެންޑް ލޯ އެންފޯސްމެންޓް، އައްޑު ސިޓީ' WHERE name = 'Noosandha - Addu';
UPDATE public.hospitals SET address_dv = 'ނޮވާ ރިސޯޓްސް، އއ. ވަކަރުފަޅި' WHERE name = 'Nova Clinic';
UPDATE public.hospitals SET address_dv = 'ހުޅުމާލެ ލޮޓް، 1193' WHERE name = 'Nowall Medical Centre';
UPDATE public.hospitals SET address_dv = 'އޯގާ މެޑިކަލް ސެންޓަރު، މ. އަސްދަ' WHERE name = 'Oagaa Medical Centre';
UPDATE public.hospitals SET address_dv = 'ޖުމީރާ މޯލްޑިވްސް އޮޅުހަޅި އައިލެންޑް' WHERE name = 'Olhahali Clinic';
UPDATE public.hospitals SET address_dv = 'ހ.ބްލޫ އަސޭރީ، މާލެ' WHERE name = 'Omega Medical Centre';

COMMIT;
