-- TEMPORARY: Update remaining doctors with transliterated Dhivehi names
-- These are approximations - replace with exact spellings when available
-- Generated for doctors that didn't match previous SQL due to name variations

BEGIN;

UPDATE public.doctors SET name_dv = 'އާމިނަތު ލަމްޙާ ޢަލީ', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Aminath Lamha Ali';
UPDATE public.doctors SET name_dv = 'ޑރ. އޭ އެފް އެމް ރަފަތުޒަމާން', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. A F M Rafatuzzaman';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމާލް ނަޖީބް', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Aamaal Najeeb';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢަބްދިކާދިރު ޙަސަން ޙުސައިން', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Abdikadir Hassan Hussein';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢަބްދުﷲ އަޙުސަން', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Abdulla Ahusan';
UPDATE public.doctors SET name_dv = 'ޑރ. އަފާފް އަޙްމަދު', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Afaaf Ahmed';
UPDATE public.doctors SET name_dv = 'ޑރ. އަފްލާ ސުހައިލް', specialty_dv = 'ރޭޑިއޮލޮޖީ' WHERE name = 'Dr. Afla Suhail';
UPDATE public.doctors SET name_dv = 'ޑރ. އަޙްމަދު އަލްކާމިލް ޙާމިދު މޫސާ', specialty_dv = 'ލޮލުގެ ބަލިތައް' WHERE name = 'Dr. Ahmad Alkamel Hamed Mosa';
UPDATE public.doctors SET name_dv = 'ޑރ. އަޙްމަދު ޢަބްދުﷲ', specialty_dv = 'ބަލިތަކަށް ފަރުވާދޭ' WHERE name = 'Dr. Ahmed Abdulla';
UPDATE public.doctors SET name_dv = 'ޑރ. އަޙްމަދު ފައިޞަލް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Ahmed Faisal';
UPDATE public.doctors SET name_dv = 'ޑރ. އަޙްމަދު މަޙްމޫދު ސާމީ އަޙްމަދު ޙުސައިން', specialty_dv = 'ކަށީގެ ބަލިތައް' WHERE name = 'Dr. Ahmed Mahmoud Sami Ahmed Hussein';
UPDATE public.doctors SET name_dv = 'ޑރ. އަޙްމަދު މިޤްދާދު', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Ahmed Migdhaadh';
UPDATE public.doctors SET name_dv = 'ޑރ. އަޙްމަދު އާރް ރަގަބް ޒުބީ', specialty_dv = 'ސާޖަރީ' WHERE name = 'Dr. Ahmed R Ragab Zubi';
UPDATE public.doctors SET name_dv = 'ޑރ. އަޙްމަދު ރަޝީދު', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Ahmed Rasheed';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢާއިޝަތު މާޝީ އިބްރާހީމް', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Aishath Maashy Ibrahim';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢާއިޝަތު ނީނާ ޝަރީފް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Aishath Neena Shareef';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢާއިޝަތު ރީމާ', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Aishath Reema';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢާއިޝަތު ސާޢާ މުޙައްމަދު', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Aishath Sa''aa Mohamed';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢާއިޝަތު ޝަފްފަފް އަޙްމަދު', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Aishath Shaffaf Ahmed';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢާއިޝަތު ޝިބާނާ އަޙްމަދު', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Aishath Shibana Ahmed';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢާއިޝަތު ޒިޔާން', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Aishath Ziyan';
UPDATE public.doctors SET name_dv = 'ޑރ. އަލާޢް ޙަސަން އަޙްމަދު އޯރާބީ', specialty_dv = 'ރޭޑިއޮލޮޖީ' WHERE name = 'Dr. Alaa Hassan Ahmed Oraby';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢަލީ ޢައްބާސް މުރުޝިދު އަބްދުޢަބްދުﷲ', specialty_dv = 'ކަށީގެ ބަލިތައް' WHERE name = 'Dr. Ali Abbas Murshed Abduabdullah';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢަލީ ޢަބްދުﷲ ލަޠީފް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Ali Abdulla Latheef';
UPDATE public.doctors SET name_dv = 'ޑރ. ޢަލީ ނަޒީމް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Ali Nazeem';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ޢާރިފާ', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Aminath Arifa';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ޙައިފާ', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Aminath Haifa';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު އިފާޝާ ގާސިމް', specialty_dv = 'ކަށީގެ ބަލިތައް' WHERE name = 'Dr. Aminath Ifasha Gasim';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު އިހުސާނާ', specialty_dv = 'ރޭޑިއޮލޮޖީ' WHERE name = 'Dr. Aminath Ihusaana';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ލިމްޔާ', specialty_dv = 'އަންހެނުންގެ ބަލިތައް' WHERE name = 'Dr. Aminath Limya';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު މިންނާ ޙުސައިން', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Aminath Minna Hussain';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު މުނަޒާ', specialty_dv = 'ބަލިތަކަށް ފަރުވާދޭ' WHERE name = 'Dr. Aminath Munaza';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ނަޒާޙާ', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Aminath Nazaaha';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ނަޒީރު', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Aminath Nazeer';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ސަލީމް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Aminath Saleem';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ސަމްޙާ', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Aminath Samha';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ޝަނާޒް ޢާދިލް', specialty_dv = 'ކުޑަކުދިންގެ ބަނޑުގެ ބަލިތައް' WHERE name = 'Dr. Aminath Shanaz Adil';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ޝައުފާ', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Aminath Shaufa';
UPDATE public.doctors SET name_dv = 'ޑރ. އާމިނަތު ޒަހްރާ', specialty_dv = 'އަންހެނުންގެ ބަލިތައް' WHERE name = 'Dr. Aminath Zahra';
UPDATE public.doctors SET name_dv = 'ޑރ. އަމްރު ރެދާ މުޙައްމަދު ބަދަވީ މަޙްމޫދު', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Amr Reda Mohamed Badawy Mahmoud';
UPDATE public.doctors SET name_dv = 'ޑރ. އަންޖަނާ ކޭ ސީ', specialty_dv = 'ޕެތޮލޮޖީ' WHERE name = 'Dr. Anjana K C';
UPDATE public.doctors SET name_dv = 'ޑރ. އަސަދު މުޙައްމަދު ޝަހީދު', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Asadh Mohamed Shaheed';
UPDATE public.doctors SET name_dv = 'ޑރ. އަޝިޝް ކައިލާޝްޗަންދުރަ ނީމާ', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Ashish Kailashchandra Nema';
UPDATE public.doctors SET name_dv = 'ޑރ. ބަސްމާ އިބްރާހީމް ސުބީރު', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Basma Ibrahim Sobir';
UPDATE public.doctors SET name_dv = 'ޑރ. ބުދީ ނާތު އަދިކާރީ ސުދީން', specialty_dv = 'ޕްލާސްޓިކް ސާޖަރީ' WHERE name = 'Dr. Budhi Nath Adhikari Sudhin';
UPDATE public.doctors SET name_dv = 'ޑރ. ދޭބާޝިސް ޑާސް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Debashis Das';
UPDATE public.doctors SET name_dv = 'ޑރ. ދީޕަކް ކުމާރު ސުންދަރޝް ބަޔްރާޓޭ', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Deepak Kumar Sundaresh Bhyratae';
UPDATE public.doctors SET name_dv = 'ޑރ. ދަރްމޭޝް އާރް ބަޙްޓީ', specialty_dv = 'އަންހެނުންގެ ބަލިތައް' WHERE name = 'Dr. Dharmesh R Bhatti';
UPDATE public.doctors SET name_dv = 'ޑރ. ދުސޫމާ ޢަބްދުލް ރައްޒާޤް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Dusooma Abdul Razzag';
UPDATE public.doctors SET name_dv = 'ޑރ. ފާތިމަތު ޢަބްދުﷲ ޒުހައިރު', specialty_dv = 'އަންހެނުންގެ ބަލިތައް' WHERE name = 'Dr. Fathimath Abdulla Zuhair';
UPDATE public.doctors SET name_dv = 'ޑރ. ފާތިމަތު ފަހުދާ ސައިދު', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Fathimath Fahudha Sayd';
UPDATE public.doctors SET name_dv = 'ޑރ. ފާތިމަތު ލީޝިޔާ އަޙްމަދު', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Fathimath Leeshiya Ahmed';
UPDATE public.doctors SET name_dv = 'ޑރ. ފާތިމަތު މުފްލިޙާ', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Fathimath Mufliha';
UPDATE public.doctors SET name_dv = 'ޑރ. ފާތިމަތު ނަޞީޙާ', specialty_dv = 'ކުޑަކުދިންގެ ބަލިތައް' WHERE name = 'Dr. Fathimath Nasiha';
UPDATE public.doctors SET name_dv = 'ޑރ. ފާތިމަތު ޝޫރާ', specialty_dv = 'ކަންފަތް، ނޭފަތް، ކަރުގެ ބަލިތައް' WHERE name = 'Dr. Fathimath Shoora';
UPDATE public.doctors SET name_dv = 'ޑރ. ފާތިމަތު ޝުދްފާ އިބްރާހީމް', specialty_dv = 'ރޭޑިއޮލޮޖީ' WHERE name = 'Dr. Fathmath Shudhfa Ibrahim';
UPDATE public.doctors SET name_dv = 'ޑރ. ފާތިމަތު ޒައިލް އަޒްމީލް', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Fathmath Zail Azmeel';
UPDATE public.doctors SET name_dv = 'ޑރ. ފާތިމަތު ޝަޒްމާ ރަމީޒް', specialty_dv = 'އަންހެނުންގެ ބަލިތައް' WHERE name = 'Dr. Fatimath Shazma Rameez';
UPDATE public.doctors SET name_dv = 'ޑރ. ފިރްދަސް ރަޝީދު', specialty_dv = 'ދަތުގެ ބަލިތައް' WHERE name = 'Dr. Firdhaus Rasheed';
UPDATE public.doctors SET name_dv = 'ޑރ. ޙައްމާދު އާދަމް', specialty_dv = 'ސާޖަރީ' WHERE name = 'Dr. Hammad Adam';
UPDATE public.doctors SET name_dv = 'ޑރ. ޙަނާން ޝަފީޤް', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Hanaan Shafeeq';
UPDATE public.doctors SET name_dv = 'ޑރ. ޙައްވާ އަޝްފާޙް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Hawwa Ashfah';
UPDATE public.doctors SET name_dv = 'ޑރ. ޙިޝާމާ ޢަބްދުﷲ', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Hishama Abdulla';
UPDATE public.doctors SET name_dv = 'ޑރ. ޙިޔާން ޙަބީބު', specialty_dv = 'ބަލިތަކަށް ފަރުވާދޭ' WHERE name = 'Dr. Hiyan Habeeb';
UPDATE public.doctors SET name_dv = 'ޑރ. ޙުސައިން ފައިޞަލް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Hussain Faisal';
UPDATE public.doctors SET name_dv = 'ޑރ. ޙުސައިން ޙާމިދު', specialty_dv = 'ސާޖަރީ' WHERE name = 'Dr. Hussain Hameed';
UPDATE public.doctors SET name_dv = 'ޑރ. އިބްރާހީމް ޝިބްލް އިބްރާހީމް ޝަހާބީލް އަދީން', specialty_dv = 'ރޭޑިއޮލޮޖީ' WHERE name = 'Dr. Ibrahim Shibl Ibrahim Shehabel Din';
UPDATE public.doctors SET name_dv = 'ޑރ. އިޝްވޯރު ރާޖް ދަވްކޯޓާ', specialty_dv = 'ކަންފަތް، ނޭފަތް، ކަރުގެ ބަލިތައް' WHERE name = 'Dr. Ishwor Raj Devkota';
UPDATE public.doctors SET name_dv = 'ޑރ. ޖަބީން ޢަލީ ޝަރީފް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Jabeen Ali Shareef';
UPDATE public.doctors SET name_dv = 'ޑރ. ޖަހަންގީރް އަޙްމަދު ޝައިޚް', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Jahangir Ahmed Sheikh';
UPDATE public.doctors SET name_dv = 'ޑރ. ޖުވައިރިޔާ އަޙްމަދު', specialty_dv = 'އަންހެނުންގެ ބަލިތައް' WHERE name = 'Dr. Juwairiya Ahmed';
UPDATE public.doctors SET name_dv = 'ޑރ. ޚަދީޖަތު ސާމިރާ', specialty_dv = 'ނަފްސާނީ ބަލިތައް' WHERE name = 'Dr. Khadheejath Saamira';
UPDATE public.doctors SET name_dv = 'ޑރ. ލީނާ ސަލީމް', specialty_dv = 'އަންހެނުންގެ ބަލިތައް' WHERE name = 'Dr. Leena Saleem';
UPDATE public.doctors SET name_dv = 'ޑރ. މަދީޙް މުޙައްމަދު ޙުސައިން', specialty_dv = 'އިމަޖެންސީ މެޑިސިން' WHERE name = 'Dr. Madheeh Mohamed Hussain';
UPDATE public.doctors SET name_dv = 'ޑރ. މަޙްމޫދު އަބްދުލްޢަޒީޒް މުޙައްމަދު އަލްޝަހަވީ', specialty_dv = 'ސާޖަރީ' WHERE name = 'Dr. Mahmoud Abdelaziz Mohamed Elshahawy';
UPDATE public.doctors SET name_dv = 'ޑރ. މަލޭ ހަލްދަރު ޕްލަބޮން', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Malay Halder Plabon';
UPDATE public.doctors SET name_dv = 'ޑރ. މަނޯޖް މުނިރާތިނަމް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Manoj Munirathinam';
UPDATE public.doctors SET name_dv = 'ޑރ. މަރިޔަމް އަޙްމަދު', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Mariyam Ahmed';
UPDATE public.doctors SET name_dv = 'ޑރ. މަރިޔަމް ނިޔާޒް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Mariyam Niyaz';
UPDATE public.doctors SET name_dv = 'ޑރ. މަރިޔަމް ޝަހާނާ މުފީދު', specialty_dv = 'ލޮލުގެ ބަލިތައް' WHERE name = 'Dr. Mariyam Shahana Mufeed';
UPDATE public.doctors SET name_dv = 'ޑރ. މަރިޔަމް ޝަޒްނާ', specialty_dv = 'އަންހެނުންގެ ބަލިތައް' WHERE name = 'Dr. Mariyam Shazna';
UPDATE public.doctors SET name_dv = 'ޑރ. މަރިޔަމް ޔޫމީ', specialty_dv = 'ކަށީގެ ބަލިތައް' WHERE name = 'Dr. Mariyam Yoomy';
UPDATE public.doctors SET name_dv = 'ޑރ. މައުރޫފާ ޢަބްދުލް ލަޠީފް', specialty_dv = 'ކަންފަތް، ނޭފަތް، ކަރުގެ ބަލިތައް' WHERE name = 'Dr. Mauroofa Abdul Latheef';
UPDATE public.doctors SET name_dv = 'ޑރ. މީޒާ ޙާނީ', specialty_dv = 'ކުޑަކުދިންގެ ބަލިތައް' WHERE name = 'Dr. Meeza Haany';
UPDATE public.doctors SET name_dv = 'ޑރ. މިލްޒާ ޢަބްދުލް މުޙްސިން', specialty_dv = 'ޕެތޮލޮޖީ' WHERE name = 'Dr. Milza Abdul Muhsin';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޢުތަޒް އައިމަން ސާލިޙް އަބްދުލްޢަޒީޒް', specialty_dv = 'ލޭހޮޅީގެ ސާޖަރީ' WHERE name = 'Dr. Moataz Ayman Saleh Abdelaziz';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު އާރިޝް', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Mohamed Aarish';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު އަރީދު އަބްދުލްވަޙާބު', specialty_dv = 'ކުޑަކުދިންގެ ބަލިތައް' WHERE name = 'Dr. Mohamed Areed Abdelwahab';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު އާސީލް ޖަލީލް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Mohamed Aseel Jaleel';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު އަލްޝަޢަރާވީ މުޙައްމަދު ޔުސުފް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Mohamed Elshaarawi Mohamed Youssif';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު ޙައިކަލް ޢަބްދުލްރަޙްމާން', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Mohamed Haikal Abdul Rahman';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު ޙިސާން ޙައިޔު', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Mohamed Hisan Hayyu';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު އިސްމާޢީލް', specialty_dv = 'އެނެސްތީސިއޮލޮޖީ' WHERE name = 'Dr. Mohamed Ismail';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު ކާމިލް ސުބްޙީ މުޙައްމަދު', specialty_dv = 'ސާޖަރީ' WHERE name = 'Dr. Mohamed Kamel Sobhi Mohamed';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު މާސޫލް ސިރާޖް', specialty_dv = 'ހިތުގެ ބަލިތައް' WHERE name = 'Dr. Mohamed Mausool Siraj';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު މިޝްވާރު އަޝްފާޤު', specialty_dv = 'ކަށީގެ ބަލިތައް' WHERE name = 'Dr. Mohamed Mishwaar Ashfaq';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު ޢުމަރު އަބްދުލްޢަލީމް އަޙްމަދު', specialty_dv = 'ކަށީގެ ބަލިތައް' WHERE name = 'Dr. Mohamed Omar Abdelaleem Ahmed';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު ރިފްޝާން އިސްމާޢީލް', specialty_dv = 'ސާޖަރީ' WHERE name = 'Dr. Mohamed Rifshan Ismail';
UPDATE public.doctors SET name_dv = 'ޑރ. މުޙައްމަދު ޝަފްފަފް އިސްމާޢީލް', specialty_dv = 'މެޑިކަލް އޮފިސަރުން' WHERE name = 'Dr. Mohamed Shaffaf Ismail';

COMMIT;
