-- FINAL CORRECTED: Update 174 hospitals with EXACT database names (including HF codes)
-- Generated from actual database export

BEGIN;

UPDATE public.hospitals SET name_dv = 'ފޯ ސީޒަންސް ރިސޯޓް ކުޑަ ހުރާ ކްލިނިކް' WHERE name = 'Four Seasons Resort Kuda Huraa Clinic';
UPDATE public.hospitals SET name_dv = 'ފުރަނާ ކްލިނިކް' WHERE name = 'Furana Clinic';
UPDATE public.hospitals SET name_dv = 'ފުރަވެރި ކްލިނިކް' WHERE name = 'Furaveri Clinic';
UPDATE public.hospitals SET name_dv = 'ގަންގީހި ކްލިނިކް' WHERE name = 'Gangehi Clinic HF - 23/ALP/PVT/706';
UPDATE public.hospitals SET name_dv = 'ގްރޭޓް މައިންޑްސް' WHERE name = 'Great Minds';
UPDATE public.hospitals SET name_dv = 'ގެސްޓް އެންޑް ސްޓާފް ކްލިނިކް' WHERE name = 'Guest and Staff Clinic';
UPDATE public.hospitals SET name_dv = 'ހާޖީ މެޑިކަލް ކްލިނިކް' WHERE name = 'Haajy Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ހަކުރާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Hakuraa Medical Centre';
UPDATE public.hospitals SET name_dv = 'ހަލަވެލި ކްލިނިކް' WHERE name = 'Halaveli Clinic';
UPDATE public.hospitals SET name_dv = 'ހާރޓް ކެއަރ' WHERE name = 'Heart Care';
UPDATE public.hospitals SET name_dv = 'ހެލެންގިރީ ކްލިނިކް' WHERE name = 'Helengeli Clinic';
UPDATE public.hospitals SET name_dv = 'ހޯޕް ހެލްތް ކެއަރ' WHERE name = 'Hope Health Care';
UPDATE public.hospitals SET name_dv = 'ހުދުރަންފުށި ކްލިނިކް' WHERE name = 'Hudhuranfushi Clinic';
UPDATE public.hospitals SET name_dv = 'ހުރަވަޅި ކްލިނިކް' WHERE name = 'Hurawalhi Clinic';
UPDATE public.hospitals SET name_dv = 'ޙުސައިން ޢަބްދުލް ސަމާދު މެމޮރިއަލް ކްލިނިކް' WHERE name = 'Hussain Abdul Samad Memorial Clinic';
UPDATE public.hospitals SET name_dv = 'ހުވަދޫ ތެރަޕީ ކްލިނިކް' WHERE name = 'Huvadhoo Therapy Clinic';
UPDATE public.hospitals SET name_dv = 'ހުވަފެން ފުށި ކްލިނިކް' WHERE name = 'Huvafen Fushi Clinic';
UPDATE public.hospitals SET name_dv = 'އައި ވެއަރ' WHERE name = 'I wear';
UPDATE public.hospitals SET name_dv = 'އައިއެމްޑީސީ މަލްޓި ސްޕެޝަލިޓީ ހޮސްޕިޓަލް' WHERE name = 'I.M.D.C Multi Speciality Hospital';
UPDATE public.hospitals SET name_dv = 'އައިކޭޓީޓީ މޯލްޑިވްސް' WHERE name = 'ICATT Maldives- Medical Services';
UPDATE public.hospitals SET name_dv = 'އިފުރު ކްލިނިކް' WHERE name = 'Ifuru Clinic';
UPDATE public.hospitals SET name_dv = 'އައިއެޗްޖީ މާމުނަގައު ކްލިނިކް' WHERE name = 'IHG Maamunagau Clinic';
UPDATE public.hospitals SET name_dv = 'އިމޭޖް ސެންޓަރު' WHERE name = 'Image Centre';
UPDATE public.hospitals SET name_dv = 'އިމްޕީރިއަލް މެޑިކެއަރ ސެންޓަރު' WHERE name = 'Imperial Medicare Centre';
UPDATE public.hospitals SET name_dv = 'އައިޖީއެމްއެޗް' WHERE name = 'Indira Gandhi Memorial Hospital (IGMH)';
UPDATE public.hospitals SET name_dv = 'އިންސްޓިޓިއުޓް ފޯ ކައުންސިލިންގ އެންޑް ސައިކޮތެރަޕީ' WHERE name = 'Institute For Counselling And Psychotherapy';
UPDATE public.hospitals SET name_dv = 'އިތާފުށި ކްލިނިކް' WHERE name = 'Ithaafushi Clinic';
UPDATE public.hospitals SET name_dv = 'ޖަވަކާރާ ކްލިނިކް' WHERE name = 'Jawakara Clinic';
UPDATE public.hospitals SET name_dv = 'ޖޭޕީ މެމޮރިއަލް ކްލިނިކް' WHERE name = 'JP Memorial Clinic';
UPDATE public.hospitals SET name_dv = 'ކާމް މެޑިކަލް' WHERE name = 'Kaam Medical';
UPDATE public.hospitals SET name_dv = 'ކާގި ކްލިނިކް' WHERE name = 'Kagi Clinic';
UPDATE public.hospitals SET name_dv = 'ކަނދޮޅު ކްލިނިކް' WHERE name = 'Kandolhu Clinic HF -23/ALP/PVT/713';
UPDATE public.hospitals SET name_dv = 'ކަނދޫމާ ކްލިނިކް' WHERE name = 'Kandooma Clinic';
UPDATE public.hospitals SET name_dv = 'ކަނުހުރާ ކްލިނިކް' WHERE name = 'Kanuhura Clinic';
UPDATE public.hospitals SET name_dv = 'ނޯހަބް' WHERE name = 'Knowhub';
UPDATE public.hospitals SET name_dv = 'ކޮމަންޑޫ ކްލިނިކް' WHERE name = 'Komandoo Clinic HF -23/ALP/PVT/712';
UPDATE public.hospitals SET name_dv = 'ކޮތައިފަރު ކްލިނިކް' WHERE name = 'Kothaifaru Clinic';
UPDATE public.hospitals SET name_dv = 'ކުޑަ ވިލިންގިލި' WHERE name = 'Kuda Villingili';
UPDATE public.hospitals SET name_dv = 'ކުޅުޙެލަމާ ތެރަޕީ' WHERE name = 'Kulhelama Therapy';
UPDATE public.hospitals SET name_dv = 'ކުޅުނު މެޑިކަލް ކްލިނިކް' WHERE name = 'Kulunu Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ކުނާވަޝި ކްލިނިކް' WHERE name = 'Kunaavashi Clinic';
UPDATE public.hospitals SET name_dv = 'ކުރަމަތި މެޑިކަލް ސެންޓަރު' WHERE name = 'Kuramathi Medical Centre';
UPDATE public.hospitals SET name_dv = 'ކުރެދިވަރު ކްލިނިކް' WHERE name = 'kuredivaru Clinic';
UPDATE public.hospitals SET name_dv = 'ކުރުންބާ ކްލިނިކް' WHERE name = 'Kurumba Clinic';
UPDATE public.hospitals SET name_dv = 'ލޭބް މޯލްޑިވްސް' WHERE name = 'Lab Maldives';
UPDATE public.hospitals SET name_dv = 'ލީފް އޮފް ލައިފް ކްލިނިކް' WHERE name = 'Leaf of Life Clinic';
UPDATE public.hospitals SET name_dv = 'ލޭކޮކާ މެޑިކަލް އެންޑް ރިހެބިލިޓޭޝަން ސެންޓަރު' WHERE name = 'Leykokaa Medical and Rehabilitation Centre';
UPDATE public.hospitals SET name_dv = 'ލައިފް ކެއަރ މެޑިކަލް ސެންޓަރު' WHERE name = 'Life Care Medical Centre';
UPDATE public.hospitals SET name_dv = 'ލައިފް ވެލްނެސް ކްލިނިކް' WHERE name = 'Life Wellness Clinic';
UPDATE public.hospitals SET name_dv = 'ލަކްސް މޯލްޑިވްސް ރިސޯޓް ކްލިނިކް' WHERE name = 'Lux Maldives Resort Clinic';
UPDATE public.hospitals SET name_dv = 'މާދޫ ކްލިނިކް' WHERE name = 'Maadhoo Clinic';
UPDATE public.hospitals SET name_dv = 'މާފުށިވަރު ކްލިނިކް' WHERE name = 'Maafushivaru Clinic';
UPDATE public.hospitals SET name_dv = 'މާމިގިލި ކްލިނިކް' WHERE name = 'Maamigili Clinic';
UPDATE public.hospitals SET name_dv = 'މާންދޫ މެޑިކަލް ސެންޓަރު' WHERE name = 'Maandhoo Medical Centre';
UPDATE public.hospitals SET name_dv = 'މާޔަފުށި ކްލިނިކް' WHERE name = 'Maayafushi Clinic';
UPDATE public.hospitals SET name_dv = 'މެކް މެޑިކަލް ކްލިނިކް' WHERE name = 'MACL Medical Clinic';
UPDATE public.hospitals SET name_dv = 'މަފްހާ ޑައިގްނޮސްޓިކް ސެންޓަރު' WHERE name = 'Mafhaa Diagnostic Centre';
UPDATE public.hospitals SET name_dv = 'މަގޭ ފިޒިއޯ' WHERE name = 'Magey Physio';
UPDATE public.hospitals SET name_dv = 'މޯލްޑިވްސް އަލްޓަނޭޓިވް މެޑިކަލް ސެންޓަރު' WHERE name = 'Maldives Alternative Medical Centre';
UPDATE public.hospitals SET name_dv = 'މޯލްޑިވްސް ނިއުރޯ އެންޑޮކްރައިން މެޑިކަލް ފެސިލިޓީ' WHERE name = 'Maldives Neuro Endocrine Medical Facility';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް ޑެންޓަލް ކެއަރ ސެންޓަރު' WHERE name = 'Master Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް ޑެންޓަލް ކެއަރ ސެންޓްރޯ' WHERE name = 'Master Dental Care Centro';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް މެޑިކަލް އެންޑް ޑެންޓަލް ކެއަރ ސެންޓަރު' WHERE name = 'Master Medical and Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'މެޑްހޯޕް މެޑިކަލް ސެންޓަރު' WHERE name = 'Medhope Medical Centre';
UPDATE public.hospitals SET name_dv = 'މެޑިކާ' WHERE name = 'Medica';
UPDATE public.hospitals SET name_dv = 'މެޑިކާ އެނެކްސް' WHERE name = 'Medica Annex';
UPDATE public.hospitals SET name_dv = 'މެޑިކަލް އެންޑް ހައިޕަރބާރިކް ކްލިނިކް' WHERE name = 'Medical & Hyperbaric Clinic';
UPDATE public.hospitals SET name_dv = 'މެޑިކްރެސްޓް ކްލިނިކް އެންޑް ޑައިގްނޮސްޓިކްސް' WHERE name = 'Medicrest Clinic and Diagnostics';
UPDATE public.hospitals SET name_dv = 'މެޑިފްލެކްސް ޑެންޓަލް އެންޑް މެކްސިލޮފޭޝަލް ސާޖަރީ' WHERE name = 'Mediflex Dental and Maxillofacial Surgery';
UPDATE public.hospitals SET name_dv = 'މެޑްނޮވާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Mednova Medical Center';
UPDATE public.hospitals SET name_dv = 'މީދުއްޕަރު ކްލިނިކް' WHERE name = 'Meedhupparu Clinic';
UPDATE public.hospitals SET name_dv = 'މީރު ކްލިނިކް' WHERE name = 'Meeru Clinic';
UPDATE public.hospitals SET name_dv = 'މިލައިދޫ ކްލިނިކް' WHERE name = 'Milaidhoo Clinic';
UPDATE public.hospitals SET name_dv = 'މައިންޑް ސްޕޭސް' WHERE name = 'Mind Space';
UPDATE public.hospitals SET name_dv = 'މައިންޑް ކެއަރ ކްލިނިކް' WHERE name = 'Mindcare Clinic';
UPDATE public.hospitals SET name_dv = 'މިޕްސްޓާރ' WHERE name = 'MIPSTAR';
UPDATE public.hospitals SET name_dv = 'މިރިޔަންދޫ މެޑިކަލް ސާވިސަސް' WHERE name = 'Miriandhoo Medical Services';
UPDATE public.hospitals SET name_dv = 'މޫވިންގް ކިޔުރު' WHERE name = 'Moving Cure';
UPDATE public.hospitals SET name_dv = 'އެމްޕީއައި ކްލިނިކް' WHERE name = 'MPI Clinique';
UPDATE public.hospitals SET name_dv = 'މުއްދޫ ކްލިނިކް' WHERE name = 'Mudhdhoo Clinic';
UPDATE public.hospitals SET name_dv = 'މުރަކާ ކްލިނިކް' WHERE name = 'Muraka Clinic';
UPDATE public.hospitals SET name_dv = 'މައި ކްލިނިކް' WHERE name = 'My Clinic';
UPDATE public.hospitals SET name_dv = 'މައި ޑެންޓަލް ކެއަރ' WHERE name = 'My Dental Care HF -23/ALP/PVT/710';
UPDATE public.hospitals SET name_dv = 'މައި ފެމިލީ ޑެންޓިސްޓް' WHERE name = 'My Family Dentist';
UPDATE public.hospitals SET name_dv = 'މައި ފެމިލީ ޑެންޓިސްޓް މާލެ' WHERE name = 'My Family Dentist Male''';
UPDATE public.hospitals SET name_dv = 'ނަފްސު ސައިކޮލޮޖިކަލް ސާވިސަސް' WHERE name = 'Nafsu Psychological Services';
UPDATE public.hospitals SET name_dv = 'ނައިފަރު މެޑިކަލް ސެންޓަރު' WHERE name = 'Naifaru Medical Center';
UPDATE public.hospitals SET name_dv = 'ނަޒާ ހެލްތް' WHERE name = 'NazaHealth';
UPDATE public.hospitals SET name_dv = 'ނިޔަމާ ރިސޯޓް ކްލިނިކް' WHERE name = 'Niyama Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ނޫ ކްލިނިކް' WHERE name = 'Noo Clinic';
UPDATE public.hospitals SET name_dv = 'ނޫސަންދާ' WHERE name = 'Noosandha';
UPDATE public.hospitals SET name_dv = 'ނޫސަންދާ - އައްޑު' WHERE name = 'Noosandha - Addu';
UPDATE public.hospitals SET name_dv = 'ނޮވާ ކްލިނިކް' WHERE name = 'Nova Clinic';
UPDATE public.hospitals SET name_dv = 'ނޯވޯލް މެޑިކަލް ސެންޓަރު' WHERE name = 'Nowall Medical Centre';
UPDATE public.hospitals SET name_dv = 'އޯގާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Oagaa Medical Centre';
UPDATE public.hospitals SET name_dv = 'އޮޅުހަޅި ކްލިނިކް' WHERE name = 'Olhahali Clinic';
UPDATE public.hospitals SET name_dv = 'އޮމެގާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Omega Medical Centre';
UPDATE public.hospitals SET name_dv = 'އައުޗް' WHERE name = 'Ouch';
UPDATE public.hospitals SET name_dv = 'ޕެއިން ކްލިނިކް' WHERE name = 'Pain Clinic';
UPDATE public.hospitals SET name_dv = 'ޕާރލް މެޑިކަލް ސެންޓަރު' WHERE name = 'Pearl Medical Centre';

COMMIT;
