-- Update hospitals with exact Dhivehi names based on actual database names
-- Run this in Supabase SQL Editor
-- Generated from actual database names vs CSV data

BEGIN;

-- Update hospitals with NULL name_dv using exact database names
UPDATE public.hospitals SET name_dv = 'އާހިޔާންސް މެޑިކަލް ކްލިނިކް' WHERE name = 'Aahiyans Medical Clinic';
UPDATE public.hospitals SET name_dv = 'އަބުހަރީ މެޑިކަލް ސެންޓަރު' WHERE name = 'Abuharee Medical Centre';
UPDATE public.hospitals SET name_dv = 'އޭޑީކޭ ހޮސްޕިޓަލް' WHERE name = 'ADK Hospital';
UPDATE public.hospitals SET name_dv = 'އޭޑީކޭ ހޮސްޕިޓަލް ރީޗް ކްލިނިކް، މާރަންފުށި' WHERE name = 'ADK Hospital Reach Clinic, Maaranfushi';
UPDATE public.hospitals SET name_dv = 'އެޑްވާންސް ޑައިގްނޯސްޓިކް ސެންޓަރު' WHERE name = 'Advance Diagnostic Center';
UPDATE public.hospitals SET name_dv = 'އެޑްވާންސް އައި ކްލިނިކް' WHERE name = 'Advance Eye Clinic';
UPDATE public.hospitals SET name_dv = 'އެޑްވާންސް މެޑިކަލް ކްލިނިކް' WHERE name = 'Advance Medical Clinic';
UPDATE public.hospitals SET name_dv = 'އެއިމްސް ޑައިގްނޮސްޓިކް ކެއަރ' WHERE name = 'Aims Diagnostic Care';
UPDATE public.hospitals SET name_dv = 'އަލައި ޕްލޭ އެންޑް ލަރން ތެރަޕީ ސެންޓަރު' WHERE name = 'Alai Play and Learn Therapy Center HF - 23/ALP/PVT/705';
UPDATE public.hospitals SET name_dv = 'އަލިމަތާ ކްލިނިކް' WHERE name = 'Alimatha Clinic';
UPDATE public.hospitals SET name_dv = 'އޭއެމްޑީސީ ފިޒިއޮތެރަޕީ ޑިޕާޓްމެންޓް' WHERE name = 'AMDC Physiotherapy Department';
UPDATE public.hospitals SET name_dv = 'އަމިއްލާ ސިއްޙަތު' WHERE name = 'Amilla Sihhath';
UPDATE public.hospitals SET name_dv = 'އަމިންގިރީ ކްލިނިކް' WHERE name = 'Amingiri Clinic';
UPDATE public.hospitals SET name_dv = 'އަނަންތަރާ ދިގު ކްލިނިކް' WHERE name = 'Ananatara Dhigu Clinic';
UPDATE public.hospitals SET name_dv = 'އަނަންތަރާ ކިހަވާހް ވިލާ ކްލިނިކް' WHERE name = 'Anantara Kihavah Villas Clinic';
UPDATE public.hospitals SET name_dv = 'އަންގާގާ މެޑިކަލްސް' WHERE name = 'Angaga Medicals';
UPDATE public.hospitals SET name_dv = 'އަންޒާނާ ވެލަވަރު މެޑިކަލް ސެންޓަރު' WHERE name = 'Angsana Velavaru Medical Centre';
UPDATE public.hospitals SET name_dv = 'އަސީސާ މެޑިކަލް ސެންޓަރު' WHERE name = 'Asisa Medical Center';
UPDATE public.hospitals SET name_dv = 'އަތުރުގާ މެޑިކަލް ކްލިނިކް' WHERE name = 'Athuruga Medical Clinic';
UPDATE public.hospitals SET name_dv = 'އަޔާދާ މޯލްޑިވްސް ރިސޯޓް ކްލިނިކް' WHERE name = 'Ayada Maldives Resort Clinic';
UPDATE public.hospitals SET name_dv = 'އަޒްމީ ނަޢީމް މެޑިކަލް އެންޑް ޑައިގްނޮސްޓިކް ސެންޓަރު' WHERE name = 'Azmi Naeem Medical & Diagnostic Centre';
UPDATE public.hospitals SET name_dv = 'ބަރޯސް ކްލިނިކް' WHERE name = 'Baros Clinic';
UPDATE public.hospitals SET name_dv = 'ބީކެއަރ' WHERE name = 'BCare';
UPDATE public.hospitals SET name_dv = 'ބްލިސް ކެއަރ' WHERE name = 'Bliss Care';
UPDATE public.hospitals SET name_dv = 'ބްލައިސް މަލްޓި-ސްޕެޝަލިޓީ ތެރަޕީ ސެންޓަރު' WHERE name = 'Blyss Multi-Speciality Therapy Centre';
UPDATE public.hospitals SET name_dv = 'ބޮލިފުށި ކްލިނިކް' WHERE name = 'Bolifushi Clinic';
UPDATE public.hospitals SET name_dv = 'ބުލްބުލް ތެރަޕީ ކްލިނިކް' WHERE name = 'Bulbul Therapy Clinic';
UPDATE public.hospitals SET name_dv = 'ކެއަރ މެކްސް ކްލިނިކް 1' WHERE name = 'Care Max Clinic 1';
UPDATE public.hospitals SET name_dv = 'ކެއަރ މެޑިކަލްސް ސާވިސަސް' WHERE name = 'Care Medicals Services';
UPDATE public.hospitals SET name_dv = 'ކެއަރ ޓްރަސްޓް މަލްޓި ސްޕެޝަލިޓީ ކްލިނިކް' WHERE name = 'Care Trust Multi Speciality Clinic';
UPDATE public.hospitals SET name_dv = 'ކެއަރވަން ޑެންޓަލް އެންޑް ކްލިނިކް' WHERE name = 'Careone Dental & Clinic';
UPDATE public.hospitals SET name_dv = 'ސެންޓްރަލް ކްލިނިކް' WHERE name = 'Central Clinic';
UPDATE public.hospitals SET name_dv = 'ސެންޓްރަލް މެޑިކަލް ސެންޓަރު' WHERE name = 'Central Medical Center';
UPDATE public.hospitals SET name_dv = 'ސެންޓަރ ފޯ ޓްރެޑިޝަނަލް މެޑިސިން' WHERE name = 'Centre for Traditional Medicine';
UPDATE public.hospitals SET name_dv = 'ޝެވަލް ބްލާންސް ރަންދެލި ކްލިނިކް' WHERE name = 'Cheval Blance Randeli Clinic';
UPDATE public.hospitals SET name_dv = 'ޗައިލްޑް ޑިވެލޮޕްމަންޓް ކްލިނިކް' WHERE name = 'Child Development Clinic';
UPDATE public.hospitals SET name_dv = 'ޗައިނީޒް ހެލްތް ކެއަރ' WHERE name = 'Chinese Health Care';
UPDATE public.hospitals SET name_dv = 'ސިނަމަން ދޮންވެލި މޯލްޑިވްސް މެޑިކަލް ކްލިނިކް' WHERE name = 'Cinnamon Dhonveli Maldives Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ސިނަމަން ވެލިފުށި މޯލްޑިވްސް މެޑިކަލް ކްލިނިކް' WHERE name = 'Cinnamon Velifushi Maldives Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ސިޓީ އޮޕްޓިކަލްސް' WHERE name = 'City Opticals';
UPDATE public.hospitals SET name_dv = 'ކޯކޯއިސްލަންޑް ކްލިނިކް' WHERE name = 'Cocoa Island Island';
UPDATE public.hospitals SET name_dv = 'ކޯކޮގިރީ ކްލިނިކް' WHERE name = 'Cocogiri Clinic';
UPDATE public.hospitals SET name_dv = 'ކޮންސްޓަންސް މޫފުށި ރިސޯޓް ކްލިނިކް' WHERE name = 'Constance Moofushi Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ޑީ.އެސް.އެމް ކްލިނިކް' WHERE name = 'D.S.M Clinic';
UPDATE public.hospitals SET name_dv = 'ޑެންޓަލް ކެއަރ ސެންޓަރު' WHERE name = 'Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'ޑެންޓަލް ސްޓޫޑިއޯ' WHERE name = 'Dental Studio';
UPDATE public.hospitals SET name_dv = 'ދަރަވަންދޫ މެޑިކަލް ސެންޓަރު' WHERE name = 'Dharavandhoo Medical Center';
UPDATE public.hospitals SET name_dv = 'ދިވެހި ބޭސް ކްލިނިކް' WHERE name = 'Dhivehi Beys Clinic';
UPDATE public.hospitals SET name_dv = 'ދުނިދޫ ކްލިނިކް' WHERE name = 'Dhoonidhoo Clinic';
UPDATE public.hospitals SET name_dv = 'ދުގެތި ދިވެހިބޭސް ކްލިނިކް' WHERE name = 'Dhugethi Dhivehibeys Clinic';
UPDATE public.hospitals SET name_dv = 'ޑރ. ކްލިނިކް' WHERE name = 'Doctor''s Clinic';
UPDATE public.hospitals SET name_dv = 'ޑރ. ދީދީ ޑެންޓަލް އެންޑް މެޑިކަލް ސެންޓަރު' WHERE name = 'Dr Didi Dental And Medical Center';
UPDATE public.hospitals SET name_dv = 'ޑރ. އުސާމާ ޑެންޓަލް ކްލިނިކް' WHERE name = 'Dr Usama Dental Clinic';
UPDATE public.hospitals SET name_dv = 'ޑރ. ދީދީ ޑެންޓަލް ސެންޓަރު' WHERE name = 'Dr. Didi Dental Centre';
UPDATE public.hospitals SET name_dv = 'ޑރ. ޖިހާދުގެ މެޑިކަލް އެންޑް ޑެންޓަލް ސެންޓަރު' WHERE name = 'Dr. Jihad''s Medical and Dental Centre';
UPDATE public.hospitals SET name_dv = 'ޑރ. އުސާމާގެ ކްލިނިކް މާފަންނު' WHERE name = 'Dr. Usama''s Clinic Maafannu';
UPDATE public.hospitals SET name_dv = 'ޑްރީމް ލޭންޑް ކްލިނިކް' WHERE name = 'Dream Land Clinic';
UPDATE public.hospitals SET name_dv = 'އަރލީ އިންޓަވެންޝަން ތެރަޕީ ސެންޓަރު' WHERE name = 'Early Intervention Therapy Centre';
UPDATE public.hospitals SET name_dv = 'އެލައިޓް މެޑިކަލް ސެންޓަރު' WHERE name = 'Elite Medical Centre';
UPDATE public.hospitals SET name_dv = 'އެލްލައިދޫ ކްލިނިކް' WHERE name = 'Ellaidhoo Clinic';
UPDATE public.hospitals SET name_dv = 'އެމަރަލްޑް ޑެންޓަލް ކެއަރ' WHERE name = 'Emerald Dental Care';
UPDATE public.hospitals SET name_dv = 'އެމަރަލްޑް ފާރޫޝި ކްލިނިކް' WHERE name = 'Emerald Faarushi Clinic';
UPDATE public.hospitals SET name_dv = 'އެމަރަލްޑް މޯލްޑިވްސް ރިސޯޓް ކްލިނިކް' WHERE name = 'Emerald Maldives Resort Clinic';
UPDATE public.hospitals SET name_dv = 'އެރި މޯލްޑިވްސް ކްލިނިކް' WHERE name = 'Eri Maldives Clini';
UPDATE public.hospitals SET name_dv = 'އެރިޔާދޫ ކްލިނިކް' WHERE name = 'Eriyadu Clinic';
UPDATE public.hospitals SET name_dv = 'އީވް ކްލިނިކް' WHERE name = 'Eve Clinic';
UPDATE public.hospitals SET name_dv = 'އައި ކެއަރ ކްލިނިކް (އައްޑު ބްރާންޗް)' WHERE name = 'Eye Care Clinic (Addu Branch)';
UPDATE public.hospitals SET name_dv = 'އައި ކެއަރ ހޮސްޕިޓަލް' WHERE name = 'Eye Care Hospital';
UPDATE public.hospitals SET name_dv = 'އައި ކެއަރ ހޮސްޕިޓަލް ހުޅުމާލެ އެނެކްސް' WHERE name = 'Eye Care Hospital Hulhumale'' Annex';
UPDATE public.hospitals SET name_dv = 'އައި ޓޫ އައި އޮޕްޓިކަލްސް އެންޑް ކްލިނިކް' WHERE name = 'Eye to Eye Opticals & Clinic';
UPDATE public.hospitals SET name_dv = 'އައި ޓޫ އައި އޮޕްޓިކަލްސް އެންޑް ކްލިނިކް 2' WHERE name = 'Eye to Eye Opticals & Clinic 2';
UPDATE public.hospitals SET name_dv = 'އައިކެއަރ އޮޕްޓިކަލްސް (ފުވައްމުލައް ބްރާންޗް)' WHERE name = 'Eyecare opticals (fuvahmulah branch)';
UPDATE public.hospitals SET name_dv = 'އެފް އެންޑް ސީ މެޑިކެއަރ އެންޑް ސްކޭން ސެންޓަރު' WHERE name = 'F & C Medicare and Scan Center';
UPDATE public.hospitals SET name_dv = 'އެފް އެންޑް ސީ ޕްރައިމް ކެއަރ' WHERE name = 'F & C Prime Care';
UPDATE public.hospitals SET name_dv = 'އެފް އެންޑް ސީ މެޑިކެއަރ، މީދޫ' WHERE name = 'F&C Medicare, Meedhoo';
UPDATE public.hospitals SET name_dv = 'ފެމިލީ ކެއަރ ކްލިނިކް އެންޑް ސްކޭން ސެންޓަރު' WHERE name = 'Family Care Clinic and Scan Centre';
UPDATE public.hospitals SET name_dv = 'ފެމިލީ ޑެންޓަލް ކެއަރ' WHERE name = 'Family Dental Care';
UPDATE public.hospitals SET name_dv = 'ފެމިލީ ރިލޭޝަންޝިޕް ސާވިސަސް' WHERE name = 'Family Relationship Services';
UPDATE public.hospitals SET name_dv = 'ފަރޫކް ހެލްތްކެއަރ' WHERE name = 'Farook Healthcare';
UPDATE public.hospitals SET name_dv = 'ފަރޫކް ހެލްތްކެއަރ ވިލިނގިލި' WHERE name = 'Farook Healthcare Villingili';

COMMIT;
