-- TEMPORARY: Update 150 hospitals with transliterated Dhivehi names (Batch 3)
-- These are approximations - replace with exact spellings when available
-- Generated from hospitals_batch3_template.csv

BEGIN;

UPDATE public.hospitals SET name_dv = 'ފޯ ސީޒަންސް ރިސޯޓް ކުޑަ ހުރާ ކްލިނިކް', address_dv = 'ފޯ ސީޒަންސް ރިސޯޓް މޯލްޑިވްސް އެޓް ކުޑަހުރާ' WHERE name = 'Four Seasons Resort Kuda Huraa Clinic';
UPDATE public.hospitals SET name_dv = 'ފުރަނާ ކްލިނިކް', address_dv = 'ފުރަނަފުށި އައިލެންޑް ނޮތް މާލެ އެޓޯލް' WHERE name = 'Furana Clinic';
UPDATE public.hospitals SET name_dv = 'ފުރަވެރި ކްލިނިކް', address_dv = 'ފުރަވެރި ރިސޯޓް މޯލްޑިވްސް' WHERE name = 'Furaveri Clinic';
UPDATE public.hospitals SET name_dv = 'ގަންގީހި ކްލިނިކް', address_dv = 'ގަންގީހި އައިލެންޑް ރިސޯޓް' WHERE name = 'Gangehi Clinic HF - 23/ALP/PVT/706';
UPDATE public.hospitals SET name_dv = 'ގްރޭޓް މައިންޑްސް', address_dv = 'ވާވަތި ބިލްޑިންގް' WHERE name = 'Great Minds';
UPDATE public.hospitals SET name_dv = 'ގެސްޓް އެންޑް ސްޓާފް ކްލިނިކް', address_dv = 'ގދ. ކޮނޮތްތާ' WHERE name = 'Guest and Staff Clinic';
UPDATE public.hospitals SET name_dv = 'ހާޖީ މެޑިކަލް ކްލިނިކް', address_dv = 'ސައުތް ވާރޑް، ހިކިފިނިފެންމާގެ' WHERE name = 'Haajy Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ހަކުރާ މެޑިކަލް ސެންޓަރު', address_dv = '' WHERE name = 'Hakuraa Medical Centre';
UPDATE public.hospitals SET name_dv = 'ހަލަވެލި ކްލިނިކް', address_dv = 'ކޮންސްޓަންސް ހަލަވެލި ރިސޯޓް' WHERE name = 'Halaveli Clinic';
UPDATE public.hospitals SET name_dv = 'ހާރޓް ކެއަރ', address_dv = 'ގ. އަލިދޯގެ' WHERE name = 'Heart Care';
UPDATE public.hospitals SET name_dv = 'ހެލެންގިރީ ކްލިނިކް', address_dv = 'އޮބްލޫ އެޓްމޮސްފިއަރ' WHERE name = 'Helengeli Clinic';
UPDATE public.hospitals SET name_dv = 'ހޯޕް ހެލްތް ކެއަރ', address_dv = 'ހ. ބުރުނީގެ ދެކުނުގެ' WHERE name = 'Hope Health Care';
UPDATE public.hospitals SET name_dv = 'ހުދުރަންފުށި ކްލިނިކް', address_dv = 'އަދާރަން ސިލެކްޓް' WHERE name = 'Hudhuranfushi Clinic';
UPDATE public.hospitals SET name_dv = 'ހުރަވަޅި ކްލިނިކް', address_dv = 'ހުރަވަޅި އައިލެންޑް ރިސޯޓް' WHERE name = 'Hurawalhi Clinic';
UPDATE public.hospitals SET name_dv = 'ޙުސައިން ޢަބްދުލް ސަމާދު މެމޮރިއަލް ކްލިނިކް', address_dv = 'މާޔާ، އދ. ދަންގެތި' WHERE name = 'Hussain Abdul Samad Memorial Clinic';
UPDATE public.hospitals SET name_dv = 'ހުވަދޫ ތެރަޕީ ކްލިނިކް', address_dv = 'ކޭވަކުގެ' WHERE name = 'Huvadhoo Therapy Clinic';
UPDATE public.hospitals SET name_dv = 'ހުވަފެން ފުށި ކްލިނިކް', address_dv = 'ހުވަފެންފުށި' WHERE name = 'Huvafen Fushi Clinic';
UPDATE public.hospitals SET name_dv = 'އައި ވެއަރ', address_dv = 'މ. ބްލޫ ޗިޕް' WHERE name = 'I wear';
UPDATE public.hospitals SET name_dv = 'އައިއެމްޑީސީ މަލްޓި ސްޕެޝަލިޓީ ހޮސްޕިޓަލް', address_dv = 'އޯލްބަނީ، ސ.ހިތަދޫ' WHERE name = 'I.M.D.C Multi Speciality Hospital';
UPDATE public.hospitals SET name_dv = 'އައިކޭޓީޓީ މޯލްޑިވްސް', address_dv = 'ސަކާއިމޫ ބިލްޑިންގް' WHERE name = 'ICATT Maldives- Medical Services';
UPDATE public.hospitals SET name_dv = 'އިފުރު ކްލިނިކް', address_dv = 'އިފުރު އައިލެންޑް' WHERE name = 'Ifuru Clinic';
UPDATE public.hospitals SET name_dv = 'އައިއެޗްޖީ މާމުނަގައު ކްލިނިކް', address_dv = 'މާމުނަގައު އައިލެންޑް' WHERE name = 'IHG Maamunagau Clinic';
UPDATE public.hospitals SET name_dv = 'އިމޭޖް ސެންޓަރު', address_dv = 'ހ. ޝޭޑީ ޕާލްމް' WHERE name = 'Image Centre';
UPDATE public.hospitals SET name_dv = 'އިމްޕީރިއަލް މެޑިކެއަރ ސެންޓަރު', address_dv = 'ގ. ޗަމަން' WHERE name = 'Imperial Medicare Centre';
UPDATE public.hospitals SET name_dv = 'އައިޖީއެމްއެޗް', address_dv = 'ބޮޑުތަކުރުފާނު މަގު' WHERE name = 'Indira Gandhi Memorial Hospital (IGMH)';
UPDATE public.hospitals SET name_dv = 'އިންސްޓިޓިއުޓް ފޯ ކައުންސިލިންގ އެންޑް ސައިކޮތެރަޕީ', address_dv = 'ހ.ޙައިފާ' WHERE name = 'Institute For Counselling And Psychotherapy';
UPDATE public.hospitals SET name_dv = 'އިތާފުށި ކްލިނިކް', address_dv = 'އިތާފުށި' WHERE name = 'Ithaafushi Clinic';
UPDATE public.hospitals SET name_dv = 'ޖަވަކާރާ ކްލިނިކް', address_dv = 'މަބިންހުރަ އައިލެންޑް' WHERE name = 'Jawakara Clinic';
UPDATE public.hospitals SET name_dv = 'ޖޭޕީ މެމޮރިއަލް ކްލިނިކް', address_dv = 'ރޮބިންސަން މޯލްޑިވްސް' WHERE name = 'JP Memorial Clinic';
UPDATE public.hospitals SET name_dv = 'ކާމް މެޑިކަލް', address_dv = 'ލޮޓް 10414، ހުޅުމާލެ' WHERE name = 'Kaam Medical';
UPDATE public.hospitals SET name_dv = 'ކާގި ކްލިނިކް', address_dv = 'ކާގި މޯލްޑިވްސް' WHERE name = 'Kagi Clinic';
UPDATE public.hospitals SET name_dv = 'ކަނދޮޅު ކްލިނިކް', address_dv = 'އއ. ކަނދޮޅުދޫ' WHERE name = 'Kandolhu Clinic HF -23/ALP/PVT/713';
UPDATE public.hospitals SET name_dv = 'ކަނދޫމާ ކްލިނިކް', address_dv = 'ހޮލިޑޭ އިން ރިސޯޓް' WHERE name = 'Kandooma Clinic';
UPDATE public.hospitals SET name_dv = 'ކަނުހުރާ ކްލިނިކް', address_dv = 'ކަނުހުރާ' WHERE name = 'Kanuhura Clinic';
UPDATE public.hospitals SET name_dv = 'ނޯހަބް', address_dv = 'ގ. ހިޔާކުރި' WHERE name = 'Knowhub';
UPDATE public.hospitals SET name_dv = 'ކޮމަންޑޫ ކްލިނިކް', address_dv = 'ކޮމަންޑޫ މޯލްޑިވްސް' WHERE name = 'Komandoo Clinic HF -23/ALP/PVT/712';
UPDATE public.hospitals SET name_dv = 'ކޮތައިފަރު ކްލިނިކް', address_dv = 'އަލިލާ ކޮތައިފަރު' WHERE name = 'Kothaifaru Clinic';
UPDATE public.hospitals SET name_dv = 'ކުޑަ ވިލިންގިލި', address_dv = 'ކުޑަ ވިލިންގިލި ރިސޯޓް' WHERE name = 'Kuda Villingili';
UPDATE public.hospitals SET name_dv = 'ކުޅުޙެލަމާ ތެރަޕީ', address_dv = 'މ. ކުލުނުވެހި' WHERE name = 'Kulhelama Therapy';
UPDATE public.hospitals SET name_dv = 'ކުޅުނު މެޑިކަލް ކްލިނިކް', address_dv = 'މ. ނާރިގުގަސްދޯޝުގެ' WHERE name = 'Kulunu Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ކުނާވަޝި ކްލިނިކް', address_dv = 'ނޫ އިތުރުމަގު' WHERE name = 'Kunaavashi Clinic';
UPDATE public.hospitals SET name_dv = 'ކުރަމަތި މެޑިކަލް ސެންޓަރު', address_dv = 'ކުރަމަތި ޓޫރިސްޓް ރިސޯޓް' WHERE name = 'Kuramathi Medical Centre';
UPDATE public.hospitals SET name_dv = 'ކުރެދިވަރު ކްލިނިކް', address_dv = 'މޯވެންޕިކް' WHERE name = 'kuredivaru Clinic';
UPDATE public.hospitals SET name_dv = 'ކުރުންބާ ކްލިނިކް', address_dv = 'ކުރުންބާ މޯލްޑިވްސް' WHERE name = 'Kurumba Clinic';
UPDATE public.hospitals SET name_dv = 'ލޭބް މޯލްޑިވްސް', address_dv = 'ލޮޓް ނައް 11261' WHERE name = 'Lab Maldives';
UPDATE public.hospitals SET name_dv = 'ލީފް އޮފް ލައިފް ކްލިނިކް', address_dv = 'އެންތޫރިޔަމް' WHERE name = 'Leaf of Life Clinic';
UPDATE public.hospitals SET name_dv = 'ލޭކޮކާ މެޑިކަލް އެންޑް ރިހެބިލިޓޭޝަން ސެންޓަރު', address_dv = 'ހ. މީރުބަހުރުގެ' WHERE name = 'Leykokaa Medical and Rehabilitation Centre';
UPDATE public.hospitals SET name_dv = 'ލައިފް ކެއަރ މެޑިކަލް ސެންޓަރު', address_dv = 'ރަބަރުގަސް މަގު' WHERE name = 'Life Care Medical Centre';
UPDATE public.hospitals SET name_dv = 'ލައިފް ވެލްނެސް ކްލިނިކް', address_dv = 'ހިޔާ ފުލަތު' WHERE name = 'Life Wellness Clinic';
UPDATE public.hospitals SET name_dv = 'ލަކްސް މޯލްޑިވްސް ރިސޯޓް ކްލިނިކް', address_dv = 'އދ. ދިއްދޫފިނޮޅު' WHERE name = 'Lux Maldives Resort Clinic';
UPDATE public.hospitals SET name_dv = 'މާދޫ ކްލިނިކް', address_dv = 'އޮޒެން ބައި އެޓްމޮސްފިއަރ' WHERE name = 'Maadhoo Clinic';
UPDATE public.hospitals SET name_dv = 'މާފުށިވަރު ކްލިނިކް', address_dv = '' WHERE name = 'Maafushivaru Clinic';
UPDATE public.hospitals SET name_dv = 'މާމިގިލި ކްލިނިކް', address_dv = 'ރ. މާމިގިލި' WHERE name = 'Maamigili Clinic';
UPDATE public.hospitals SET name_dv = 'މާންދޫ މެޑިކަލް ސެންޓަރު', address_dv = 'ލ. މާންދޫ' WHERE name = 'Maandhoo Medical Centre';
UPDATE public.hospitals SET name_dv = 'މާޔަފުށި ކްލިނިކް', address_dv = 'މާޔަފުށި ޓޫރިސްޓް ރިސޯޓް' WHERE name = 'Maayafushi Clinic';
UPDATE public.hospitals SET name_dv = 'މެކް މެޑިކަލް ކްލިނިކް', address_dv = 'ވެލާނާ އިންޓަރނޭޝަނަލް އެއަރޕޯޓް' WHERE name = 'MACL Medical Clinic';
UPDATE public.hospitals SET name_dv = 'މަފްހާ ޑައިގްނޮސްޓިކް ސެންޓަރު', address_dv = 'މާލެ ގްރޭންޑް' WHERE name = 'Mafhaa Diagnostic Centre';
UPDATE public.hospitals SET name_dv = 'މަގޭ ފިޒިއޯ', address_dv = 'ނައިން ހައުސް' WHERE name = 'Magey Physio';
UPDATE public.hospitals SET name_dv = 'މޯލްޑިވްސް އަލްޓަނޭޓިވް މެޑިކަލް ސެންޓަރު', address_dv = 'މ. އަލުވިމާގެ އާގެ' WHERE name = 'Maldives Alternative Medical Centre';
UPDATE public.hospitals SET name_dv = 'މޯލްޑިވްސް ނިއުރޯ އެންޑޮކްރައިން މެޑިކަލް ފެސިލިޓީ', address_dv = 'ގ. މާޖެހި އެނެކްސް' WHERE name = 'Maldives Neuro Endocrine Medical Facility';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް ޑެންޓަލް ކެއަރ ސެންޓަރު', address_dv = 'ގ. ކުދިތިޔަރާ' WHERE name = 'Master Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް ޑެންޓަލް ކެއަރ ސެންޓްރޯ', address_dv = 'ސެންޓްރޯ މިނި ހޮލް' WHERE name = 'Master Dental Care Centro';
UPDATE public.hospitals SET name_dv = 'މާސްޓަރް މެޑިކަލް އެންޑް ޑެންޓަލް ކެއަރ ސެންޓަރު', address_dv = 'ޖިހާދު' WHERE name = 'Master Medical and Dental Care Centre';
UPDATE public.hospitals SET name_dv = 'މެޑްހޯޕް މެޑިކަލް ސެންޓަރު', address_dv = 'މާ. ޕިންނަކަލް' WHERE name = 'Medhope Medical Centre';
UPDATE public.hospitals SET name_dv = 'މެޑިކާ', address_dv = 'މ. ދަހަނާ' WHERE name = 'Medica';
UPDATE public.hospitals SET name_dv = 'މެޑިކާ އެނެކްސް', address_dv = 'ދާފް ސްޓޯރް' WHERE name = 'Medica Annex';
UPDATE public.hospitals SET name_dv = 'މެޑިކަލް އެންޑް ހައިޕަރބާރިކް ކްލިނިކް', address_dv = 'ކުރެދު އައިލެންޑް' WHERE name = 'Medical & Hyperbaric Clinic';
UPDATE public.hospitals SET name_dv = 'މެޑިކްރެސްޓް ކްލިނިކް އެންޑް ޑައިގްނޮސްޓިކްސް', address_dv = 'ނ. ވެލިދޫ' WHERE name = 'Medicrest Clinic and Diagnostics';
UPDATE public.hospitals SET name_dv = 'މެޑިފްލެކްސް ޑެންޓަލް އެންޑް މެކްސިލޮފޭޝަލް ސާޖަރީ', address_dv = 'މ. މާޔާ' WHERE name = 'Mediflex Dental and Maxillofacial Surgery';
UPDATE public.hospitals SET name_dv = 'މެޑްނޮވާ މެޑިކަލް ސެންޓަރު', address_dv = 'މ. އާދިއްލީގެ' WHERE name = 'Mednova Medical Center';
UPDATE public.hospitals SET name_dv = 'މީދުއްޕަރު ކްލިނިކް', address_dv = 'ރ. މީދުއްޕަރު' WHERE name = 'Meedhupparu Clinic';
UPDATE public.hospitals SET name_dv = 'މީރު ކްލިނިކް', address_dv = 'މީރު އައިލެންޑް' WHERE name = 'Meeru Clinic';
UPDATE public.hospitals SET name_dv = 'މިލައިދޫ ކްލިނިކް', address_dv = 'މިލައިދޫ' WHERE name = 'Milaidhoo Clinic';
UPDATE public.hospitals SET name_dv = 'މައިންޑް ސްޕޭސް', address_dv = 'މ. ލޮޖް' WHERE name = 'Mind Space';
UPDATE public.hospitals SET name_dv = 'މައިންޑް ކެއަރ ކްލިނިކް', address_dv = 'ހ. މީދޫ' WHERE name = 'Mindcare Clinic';
UPDATE public.hospitals SET name_dv = 'މިޕްސްޓާރ', address_dv = 'މާ. ކިނާރާ ހައުސް' WHERE name = 'MIPSTAR';
UPDATE public.hospitals SET name_dv = 'މިރިޔަންދޫ މެޑިކަލް ސާވިސަސް', address_dv = 'މިރިޔަންދޫ' WHERE name = 'Miriandhoo Medical Services';
UPDATE public.hospitals SET name_dv = 'މޫވިންގް ކިޔުރު', address_dv = 'ހ. ބަންޑޮސްގެ' WHERE name = 'Moving Cure';
UPDATE public.hospitals SET name_dv = 'އެމްޕީއައި ކްލިނިކް', address_dv = 'މާދިފުޝި' WHERE name = 'MPI Clinique';
UPDATE public.hospitals SET name_dv = 'މުއްދޫ ކްލިނިކް', address_dv = 'ބ. މުއްދޫ' WHERE name = 'Mudhdhoo Clinic';
UPDATE public.hospitals SET name_dv = 'މުރަކާ ކްލިނިކް', address_dv = 'ޖެ ޑަބްލިއު މެރިއޯޓް' WHERE name = 'Muraka Clinic';
UPDATE public.hospitals SET name_dv = 'މައި ކްލިނިކް', address_dv = 'މާ. މިލާނޯ' WHERE name = 'My Clinic';
UPDATE public.hospitals SET name_dv = 'މައި ޑެންޓަލް ކެއަރ', address_dv = 'މާމިގިލި ކައުންސިލް' WHERE name = 'My Dental Care HF -23/ALP/PVT/710';
UPDATE public.hospitals SET name_dv = 'މައި ފެމިލީ ޑެންޓިސްޓް', address_dv = 'ހިޔާ ހުޅުމާލެ' WHERE name = 'My Family Dentist';
UPDATE public.hospitals SET name_dv = 'މައި ފެމިލީ ޑެންޓިސްޓް މާލެ', address_dv = 'ހ. ގްލިސްޓަރު' WHERE name = 'My Family Dentist Male''';
UPDATE public.hospitals SET name_dv = 'ނަފްސު ސައިކޮލޮޖިކަލް ސާވިސަސް', address_dv = '' WHERE name = 'Nafsu Psychological Services';
UPDATE public.hospitals SET name_dv = 'ނައިފަރު މެޑިކަލް ސެންޓަރު', address_dv = 'ވައިޓް ބިލްޑިންގް' WHERE name = 'Naifaru Medical Center';
UPDATE public.hospitals SET name_dv = 'ނަޒާ ހެލްތް', address_dv = 'ރޯސް ގާޑަން' WHERE name = 'NazaHealth';
UPDATE public.hospitals SET name_dv = 'ނިޔަމާ ރިސޯޓް ކްލިނިކް', address_dv = 'ނިޔަމާ މޯލްޑިވްސް' WHERE name = 'Niyama Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ނޫ ކްލިނިކް', address_dv = 'ރޮބިންސަން ނޫނު' WHERE name = 'Noo Clinic';
UPDATE public.hospitals SET name_dv = 'ނޫސަންދާ', address_dv = 'މ. އިސްކަންދަރު ކޮށި' WHERE name = 'Noosandha';
UPDATE public.hospitals SET name_dv = 'ނޫސަންދާ - އައްޑު', address_dv = 'އައްޑު ސިޓީ' WHERE name = 'Noosandha - Addu';
UPDATE public.hospitals SET name_dv = 'ނޮވާ ކްލިނިކް', address_dv = 'ނޮވާ ރިސޯޓްސް' WHERE name = 'Nova Clinic';
UPDATE public.hospitals SET name_dv = 'ނޯވޯލް މެޑިކަލް ސެންޓަރު', address_dv = 'ހުޅުމާލެ ލޮޓް 1193' WHERE name = 'Nowall Medical Centre';
UPDATE public.hospitals SET name_dv = 'އޯގާ މެޑިކަލް ސެންޓަރު', address_dv = 'މ. އަސްދާ' WHERE name = 'Oagaa Medical Centre';
UPDATE public.hospitals SET name_dv = 'އޮޅުހަޅި ކްލިނިކް', address_dv = 'ޖުމެއިރާ މޯލްޑިވްސް' WHERE name = 'Olhahali Clinic';
UPDATE public.hospitals SET name_dv = 'އޮމެގާ މެޑިކަލް ސެންޓަރު', address_dv = 'ހ.ބްލޫ އަސޭރި' WHERE name = 'Omega Medical Centre';
UPDATE public.hospitals SET name_dv = 'އައުޗް', address_dv = 'ފެސްދު އައިލެންޑް' WHERE name = 'Ouch';
UPDATE public.hospitals SET name_dv = 'ޕެއިން ކްލިނިކް', address_dv = 'ގ. ހިޔާކުރި' WHERE name = 'Pain Clinic';
UPDATE public.hospitals SET name_dv = 'ޕާރލް މެޑިކަލް ސެންޓަރު', address_dv = 'މ. ޗަންބޭލީގެ' WHERE name = 'Pearl Medical Centre';
UPDATE public.hospitals SET name_dv = 'ޕާރލް މެޑިކަލް ސެންޓަރު ހުޅުމާލެ', address_dv = 'ލޮޓް ނައް 10059' WHERE name = 'Pearl Medical Centre Hulhumale';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ އެންޑް އޮޓިޒަމް ކްލިނިކް', address_dv = 'ޕްލޮޓް ނައް 10531' WHERE name = 'Physio & Autism Clinic - Hulhumale''';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ އެންޑް އޮޓިޒަމް ކްލިނިކް', address_dv = 'މ. ސައުމާމުގެ' WHERE name = 'Physio and Autism Clinic';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކްލިނިކް', address_dv = 'މ. ފިނިފަރު' WHERE name = 'Physio Clinic';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކްލިނިކް އެނެކްސް 1', address_dv = 'އެފްޑަބްލިއު ރެޒިޑެންސް' WHERE name = 'Physio Clinic Annex 1';
UPDATE public.hospitals SET name_dv = 'ފިޒިއޯ ކިޔުރު', address_dv = 'ހ. ފައިޔުކުރި' WHERE name = 'Physio Cure';
UPDATE public.hospitals SET name_dv = 'ޕައިން ޓްރީ މެޑިކް ކެއަރ', address_dv = 'ހ. އަލްމާސް ވިލާ' WHERE name = 'Pine tree Medic Care';
UPDATE public.hospitals SET name_dv = 'ޕައިން ޓްރީ މެޑިކް ކެއަރ', address_dv = 'ޝ. ފުނަދޫ' WHERE name = 'Pine tree Medic Care/ Sh. Funadhoo';
UPDATE public.hospitals SET name_dv = 'ޕޮޕިޔުލާ ކްލިނިކް', address_dv = 'ގ. ގަވަލި' WHERE name = 'Popular Clinic';
UPDATE public.hospitals SET name_dv = 'ޕްރޯ ކެއަރ ކްލިނިކް އެންޑް ޑެންޓަލް ސެންޓަރު', address_dv = 'އދ. މަހިބަދޫ' WHERE name = 'Pro Care Clinic and Dental Centre';
UPDATE public.hospitals SET name_dv = 'ޕުލްމަން މޯލްޑިވްސް މާމުތާ ރިސޯޓް ކްލިނިކް', address_dv = 'ގއ. މާމުތާ' WHERE name = 'Pullman Maldives Maamutaa Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ކުއީން އެސްތެޓިކް މެޑިކަލް ސެންޓަރު', address_dv = 'އާރ13-05' WHERE name = 'Queen Aesthetic Medical Center';
UPDATE public.hospitals SET name_dv = 'ރާޔާ ކްލިނިކް', address_dv = 'ރ. ކުޑަކުރަތު' WHERE name = 'Raaya Clinic';
UPDATE public.hospitals SET name_dv = 'ރެފްލްސް ކްލިނިކް', address_dv = 'ރެފްލްސް މޯލްޑިވްސް' WHERE name = 'Raffles Clinic';
UPDATE public.hospitals SET name_dv = 'ރަންގާލި ކްލިނިކް', address_dv = 'ކޮންރާދް މޯލްޑިވްސް' WHERE name = 'Rangali Clinic';
UPDATE public.hospitals SET name_dv = 'ރަންނާލި ކްލިނިކް', address_dv = 'އަދާރަން ކްލަބް' WHERE name = 'Rannalhi Clinic HF22/ALP/PVT/659';
UPDATE public.hospitals SET name_dv = 'ރަސްފުށި ކްލިނިކް', address_dv = '' WHERE name = 'Rasfushi Clinic';
UPDATE public.hospitals SET name_dv = 'ރީތި ބީޗް ކްލިނިކް', address_dv = 'ބ. ފޮނިމަގުދޫ' WHERE name = 'Reethi Beach Clilnic HF -23/ALP/PVT/711';
UPDATE public.hospitals SET name_dv = 'ރީތި ފަރު ކްލިނިކް', address_dv = 'ރ. ފިއްލައިދޫ' WHERE name = 'Reethi Faru Clinic';
UPDATE public.hospitals SET name_dv = 'ރިސޯޓް ކްލިނިކް', address_dv = 'ފޯ ސީޒަންސް ލަންޑާ' WHERE name = 'Resort Clinic';
UPDATE public.hospitals SET name_dv = 'ރިސޯޓް މެޑިކަލް އެންޑް ލެބޮރޭޓްރީ ސާވިސަސް', address_dv = 'މ. ޗަންބޭލީގެ' WHERE name = 'Resort Medical and Laboratory Services';
UPDATE public.hospitals SET name_dv = 'ރިވައިވް މެޑިކަލް ސެންޓަރު', address_dv = 'ހއ. ހޯރަފުށި' WHERE name = 'Revive Medical Centre';
UPDATE public.hospitals SET name_dv = 'އާރއެމްއެލް އެސް ލැބް ސާވިސަސް', address_dv = 'ނިއު ހިޔާ' WHERE name = 'RMLS Lab Services';
UPDATE public.hospitals SET name_dv = 'ރުގަލު ކްލިނިކް', address_dv = 'ވައްކަރު މޯލްޑިވްސް' WHERE name = 'Ruhgalu Clinic';
UPDATE public.hospitals SET name_dv = 'އާރއެކްސް މެޑިކެއަރ', address_dv = 'ކާލަޖް' WHERE name = 'Rx Medicare';
UPDATE public.hospitals SET name_dv = 'ސަންޑީސް ބަތަލާ އިންފަރމަރީ', address_dv = 'އއ. އެޓޯލް' WHERE name = 'Sandies Bathala Infirmary';
UPDATE public.hospitals SET name_dv = 'ޝާ ތެރަޕީ ދިވެހިބޭސް ސެންޓަރު', address_dv = 'ހުޅުމާލެ ލޮޓް 11095' WHERE name = 'Sha Therapy Dhivehibeys Centre';
UPDATE public.hospitals SET name_dv = 'ޝިފާ މެޑިކަލް', address_dv = 'ގ. ހިޔާކުރި' WHERE name = 'Shifaa Medical';
UPDATE public.hospitals SET name_dv = 'ސިކްސް ސެންސިސް ލާމު ކްލިނިކް', address_dv = 'ސިކްސް ސެންސިސް ލާމު' WHERE name = 'Six Sensus Laamu Clinic';
UPDATE public.hospitals SET name_dv = 'ސިޔާމް ވޯރްލްޑް މޯލްޑިވްސް ކްލިނިކް', address_dv = 'ނ. ދިގުރާ' WHERE name = 'Siyam World Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސްމައިލްސް ޑެންޓަލް ކެއަރ', address_dv = 'މާ. ވާވަތި' WHERE name = 'Smiles Dental Care';
UPDATE public.hospitals SET name_dv = 'ސްމައިލްސް ޑެންޓަލް ކެއަރ ހުޅުމާލެ', address_dv = 'ލޮޓް 11000' WHERE name = 'Smiles Dental Care Hulhumale''';
UPDATE public.hospitals SET name_dv = 'އެސްއޯ މޯލްޑިވްސް ކްލިނިކް', address_dv = 'އެމްބޫދޫ ލަގޫން' WHERE name = 'SO/ Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސޮނެވާ ފުށި ކްލިނިކް', address_dv = 'ސޮނެވާ ފުށި' WHERE name = 'Soneva Fushi Clinic';
UPDATE public.hospitals SET name_dv = 'ސޮނެވާ ޖާނި ކްލިނިކް', address_dv = 'ނޫނު އެޓޯލް' WHERE name = 'Soneva Jani Clinic';
UPDATE public.hospitals SET name_dv = 'ސައުތަން ކެއަރ ކްލިނިކް', address_dv = 'ސ. ހިތަދޫ' WHERE name = 'Southern Care Clinic';
UPDATE public.hospitals SET name_dv = 'ސްޓާރް މެޑިކަލް', address_dv = 'މ. ގޯލްޑަން ވެލީ' WHERE name = 'Star Medical';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް އިރުފުށި މޯލްޑިވްސް ކްލިނިކް', address_dv = 'ނޫނު އެޓޯލް' WHERE name = 'Sun Siyam Irufushi Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް އިރުވެލި މޯލްޑިވްސް ކްލިނިކް', address_dv = 'އިރުވެލި ރިސޯޓް' WHERE name = 'Sun Siyam Iruveli Maldives Clinic HF -23/ALP/PVT/709';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް އޮޅުވެލި މޯލްޑިވްސް ކްލިނިކް', address_dv = 'ކ. އޮޅުވެލި' WHERE name = 'Sun Siyam Olhuveli Maldives Clinic';
UPDATE public.hospitals SET name_dv = 'ސަން ސިޔާމް ވިލު ރީފް މޯލްޑިވްސް ކްލިނިކް', address_dv = 'ދ. މީދުފުށި' WHERE name = 'Sun Siyam Vilu Reef Maldives CLinic';
UPDATE public.hospitals SET name_dv = 'ސިނަރްޖީ ކެއަރ', address_dv = 'އެޗްސިކްސް ޓަވަރު' WHERE name = 'Synergy Care';
UPDATE public.hospitals SET name_dv = 'ތާޖް އެކްޒޮޓިކާ ކްލިނިކް', address_dv = 'ކ. އެމްބޫދޫފިނޮޅު' WHERE name = 'Taj Exotica Clinic';
UPDATE public.hospitals SET name_dv = 'ދަ ރެޒިޑެންސް މޯލްޑިވްސް އެޓް ދިގުރާ ކްލިނިކް', address_dv = 'ގއ. ދިގުރާ' WHERE name = 'The Residence Maldives at Dhigurah Clinic';
UPDATE public.hospitals SET name_dv = 'ދަ ސްޓެންޑާޑް ކްލިނިކް', address_dv = 'ހުރުވަޅި މޯލްޑިވްސް' WHERE name = 'The Standard Clinic';
UPDATE public.hospitals SET name_dv = 'ތެރަޕީ ސެންޓަރު', address_dv = 'މ. ޖޭމުގެ' WHERE name = 'Therapy Centre';
UPDATE public.hospitals SET name_dv = 'ތިލަމާފުށި ކްލިނިކް', address_dv = 'ޅ. ތިލަމާފުށި' WHERE name = 'Thilamaafushi Clinic';
UPDATE public.hospitals SET name_dv = 'ތުނޑުފުށި މެޑިކަލް ކްލިނިކް', address_dv = 'ޑައިމަންޑްސް ތުނޑުފުށި' WHERE name = 'Thudufushi Medical Clinic';
UPDATE public.hospitals SET name_dv = 'ތުޅަގިރި ކްލިނިކް', address_dv = 'ކ. ތުޅަގިރި' WHERE name = 'Thulhagiri Clinic';
UPDATE public.hospitals SET name_dv = 'ޓައިނީ ޑްރޮޕްސް މެޑިކަލް ސާވިސަސް', address_dv = 'މާ. ދުންބުގެ' WHERE name = 'Tiny Drops Medical Services';
UPDATE public.hospitals SET name_dv = 'ޓޮޓަލްފިޒިއޯ', address_dv = 'ހ. ސަކީނާ މަންޒިލް' WHERE name = 'TotalPhysio';
UPDATE public.hospitals SET name_dv = 'ޓްރޫ ކެއަރ މެޑިކަލްސް', address_dv = 'މ. ސްޕެޓުލާ' WHERE name = 'True Care Medicals';
UPDATE public.hospitals SET name_dv = 'ޓީޓީއެޗް ކްލިނިކް', address_dv = 'މ. ޗަމްޕާ ވިލާ' WHERE name = 'TTH Clinic';
UPDATE public.hospitals SET name_dv = 'ވާދޫ ކްލިނިކް', address_dv = 'އަދާރަން ޕްރެސްޓީޖް' WHERE name = 'Vadoo Clinic HF -23/ALP/PVT/708';
UPDATE public.hospitals SET name_dv = 'ވަރު މެޑިކަލް ސެންޓަރު', address_dv = 'ކ. މާދިވަރު' WHERE name = 'Varu Medical Centre';
UPDATE public.hospitals SET name_dv = 'ވީކެއަރ ކައުންސިލިންގ އެންޑް ސައިކޮތެރަޕީ ސެންޓަރު', address_dv = 'ވިލާ ކޮލެޖް' WHERE name = 'VCare Counselling and Psychotherapy Centre';
UPDATE public.hospitals SET name_dv = 'ވެލާ ޕްރައިވެޓް އައިލެންޑް ކްލިނިކް', address_dv = 'ނ. ފުށިވެލާވަރު' WHERE name = 'Velaa Private Island Clinic';
UPDATE public.hospitals SET name_dv = 'ވެލަސަރު މެޑިކަލް ސެންޓަރު', address_dv = 'ކ. ވެލަސަރު' WHERE name = 'Velassaru Medical Center';
UPDATE public.hospitals SET name_dv = 'ވެލިގަނޑު ކްލިނިކް', address_dv = 'ވެލިގަނޑު' WHERE name = 'Veligandu Clinic HF -23/ALP/PVT/704';
UPDATE public.hospitals SET name_dv = 'ވެރސޯ މެޑިކަލްސެންޓަރު އަލިފުށި', address_dv = 'ރ. އަލިފުށި' WHERE name = 'Verso MedicalCentre Alifushi';
UPDATE public.hospitals SET name_dv = 'ވިލާ ބައިޔޯ މެޑިކަލްސް ލެބޯރޭޓްރީ', address_dv = 'އދ. ނަލަގުރައިދޫ' WHERE name = 'Villa Bio Medicals Laboratory';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކެއަރ އޮޕްޓިކަލް އެންޑް އައި ކްލިނިކް', address_dv = 'ގއ. ވިލިންގިލި' WHERE name = 'Vision Care Optical and Eye Clinic';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް', address_dv = 'މ. ޝުރާ މަންޒިލް' WHERE name = 'Vision Clinic';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް ހުޅުމާލެ', address_dv = 'ހިރީފަން ގިފިލާ' WHERE name = 'Vision Clinic Hulhumale''';
UPDATE public.hospitals SET name_dv = 'ވިޔަން ކްލިނިކް-1', address_dv = 'ހ. ލަންދޫގެ' WHERE name = 'Vision Clinic-1';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ', address_dv = 'ގ. ކަނޑުވާގެ' WHERE name = 'Vital Care';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ ކުޅުދުއްފުށި އެނެކްސް', address_dv = 'ކުޅުދުއްފުށި' WHERE name = 'Vital Care Kulhudhufushi Anex';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލް ކެއަރ- ކުޅުދުއްފުށި', address_dv = 'ކުޅުދުއްފުށި' WHERE name = 'Vital Care- Kulhudhuffushi';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލްކެއަރ ޑެންޓަލް', address_dv = 'ހުޅުމާލެ، އެންދެރި' WHERE name = 'VitalCare Dental';
UPDATE public.hospitals SET name_dv = 'ވައިޓަލްކެއަރ ހުވަދޫ', address_dv = 'ގ. ކަނޑުވާގެ' WHERE name = 'Vitalcare Huvadhoo';
UPDATE public.hospitals SET name_dv = 'ވިވާޑެންޓް ޑެންޓަލް ސެންޓަރު', address_dv = 'ގ. ނަޝާތު ވިލާ' WHERE name = 'Vivadent Dental Center';
UPDATE public.hospitals SET name_dv = 'ވޮމުލި ކްލިނިކް', address_dv = 'ސެއިންޓް ރިގިސް ވޮމުލި' WHERE name = 'Vommuli Clinic';
UPDATE public.hospitals SET name_dv = 'ވެލްކެއަރ ފިޒިއޮތެރަޕީ އެންޑް ސްޕޯޓްސް ރިހެބިލިޓޭޝަން', address_dv = 'އާރ14/05' WHERE name = 'Wellcare Physiotherapy & Sports Rehabilitation';
UPDATE public.hospitals SET name_dv = 'ޔޫ އެންޑް މީ ކްލިނިކް', address_dv = 'ރ. އުތުރުމާފުށި' WHERE name = 'You & Me Clinic';

COMMIT;
